#!/bin/bash

# syncthing backup
SYNC='/media/bryan/hercules/backup/Sync/daily'
[ -d $SYNC ] || mkdir -p $SYNC
rsync -av --delete /home/bryan/Sync/ $SYNC
date > $SYNC/backup.txt

# etc backup
ETC='/media/bryan/hercules/backup/etc/daily'
[ -d $ETC ] || mkdir -p $ETC
rsync -av --delete /etc/ $ETC
date > $ETC/backup.txt

# var backup
VAR='/media/bryan/hercules/backup/var/daily'
[ -d $VAR ] || mkdir -p $VAR
rsync -av --delete /var/ $VAR
date > $VAR/backup.txt
