#!/bin/bash

/usr/bin/updatedb
/home/bryan/.local/bin/etc-generator
/home/bryan/.local/bin/clean_filesystem
/home/bryan/.local/bin/zopen -C -q
/home/bryan/.local/bin/mopen -C

# zopen and mopen create log files owned by root.
chown bryan:bryan /var/tmp/*.log
