#!/usr/bin/bash

source /home/bryan/Sync/bin/cron.jobs/backup.sh

function main() {
    ETBB=$((60 * 60 * 20)) # seconds in 20 hours (to give anacron more breathing room)

    backup /bin bin/daily "${DEFAULT_R}"
    backup /boot boot/daily "${DEFAULT_R}"
    backup /etc etc/daily "${DEFAULT_R}"
    backup_home daily "${DEFAULT_R}"
    backup /lib32 lib32/daily "${DEFAULT_R}"
    backup /lib64 lib64/daily "${DEFAULT_R}"
    backup /opt opt/daily "${DEFAULT_R}"
    backup /sbin sbin/daily "${DEFAULT_R}"
    backup /usr usr/daily "${DEFAULT_R}"
    backup /var var/daily "${DEFAULT_R}"

    post_backup_hook
}

main "$@"
