#!/bin/bash

# syncthing backup
SYNC=/media/bryan/hercules/backup/Sync/daily
[ -d $SYNC ] || mkdir -p $SYNC
rsync -av --delete --exclude 'var/projects/edgelp' /home/bryan/Sync/ $SYNC
date > $SYNC/backup.txt

# etc backup
ETC=/media/bryan/hercules/backup/etc/daily
[ -d $ETC ] || mkdir -p $ETC
rsync -av --delete /etc/ $ETC
date > $ETC/backup.txt
