#!/bin/bash

/usr/bin/updatedb
/home/bryan/.local/bin/etc-generator
/home/bryan/.local/bin/clean_filesystem
/home/bryan/.local/bin/zopen -C -q
/home/bryan/.local/bin/mopen -C
/home/bryan/.local/bin/merge_rocketbook_notes
