#!/usr/bin/bash

export SCRIPTNAME="daily_jobs"
source /home/bryan/Sync/bin/cron.jobs/jobs.sh

function main() {
    unsafe_cmd "sort_qb_quickmarks"
    unsafe_cmd "clean_recent_file_log"
    unsafe_cmd "clean_mpv_history"
    unsafe_cmd "cache_cheaders"

    return "${EC}"
}

main "$@"
