#!/bin/bash

# syncthing backup
SYNC=/media/bryan/hercules/backup/Sync/weekly
[ -d $SYNC ] || mkdir -p $SYNC
rsync -av --delete --exclude 'var/projects/edgelp' /home/bryan/Sync/ $SYNC
date > $SYNC/backup.txt

# etc backup
ETC=/media/bryan/hercules/backup/etc/weekly
[ -d $ETC ] || mkdir -p $ETC
rsync -av --delete /etc/ $ETC
date > $ETC/backup.txt

# kernel config backup
cp /usr/src/linux/.config /media/bryan/hercules/backup/kernel-config-"$(uname -r)"
