#!/bin/bash

# Allows me to have a .localaliases file in any directory that I want which
# can be used to customize bash commands locally.

LocalAlias () {
    GLOBAL="$HOME/.globalaliases"
    LOCAL="./.localaliases"
    CMD=${1,}
    NEWCMD=

    if [ -a $LOCAL ]; then
        NEWCMD+=$(grep -i "$CMD" "$LOCAL")
        if [ -n "$NEWCMD" ]; then
            FOUND=1 # CMD already exists in .args
        else
            FOUND=0
        fi
    else
        FOUND=0
    fi


    if [ -a $GLOBAL ]; then
        GGREP=$(grep -i "$CMD" "$GLOBAL")
        NEWCMD+=${GGREP/$CMD}
    else
        : # GLOBAL doesn't exist and this script will not create it.
    fi


    if [ $FOUND -eq 0 ]; then
        printf "Map the ${CMD^} command to the ${CMD} command? (y/n): "
        read -n 1 CHOICE
        echo

        if [ $CHOICE != "y" ]; then
            exit 1
        fi

        printf "${CMD^} --> ${CMD} "
        read ARGS
        printf "$CMD $ARGS\n" >> $LOCAL
    else
        printf "${CMD^} ---> $NEWCMD\n"
        eval $NEWCMD
    fi
}
