#!/bin/bash

# Allows me to have a .localaliases file in any directory that I want which
# can be used to customize bash commands locally.

LocalAlias () {
    FILE="./.localaliases"
    ALIAS=$1
    GREP=$2
    CMD=${GREP/"$ALIAS"" ---> "}

    if [ -n "$CMD" ]; then
        printf "$GREP\n$CMD"
        eval "$CMD"
        exit 1
    else
        printf "Create a new local alias for $ALIAS? (y/n): "
        read -n 1 CHOICE
        echo

        if [ $CHOICE != "y" ]; then
            exit 0
        fi

        printf "$ALIAS ---> "
        read CMD
        printf "$ALIAS ---> $CMD \n" >> $FILE
        exit 1
    fi
}
