#!/bin/bash
if [[ $(hostname) == "aphrodite" ]]; then
	cd /home/bryan/Dropbox/logs/aphrodite-motion
	N=30
	M=1
else
	cd /home/bryan/motion
	N=300
	M=5
fi

(sleep $N && motion) &
PID=$!

scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
i3lock -n -i /tmp/screenshotblur.png

kill $PID
pkill motion

touch -t $(date --date="$M minute ago" +%Y%m%d%H%M) /tmp/motionts
find . -newer /tmp/motionts -name "*.avi" -delete
find . -name "*.avi" -size -500k -delete
