#!/bin/bash
if pgrep -f panel > /dev/null; then
    pids=( $(pgrep -f panel) )
    for pid in "${pids[@]}"; do
        if [[ $pid != $$ ]]; then
            kill "$pid"
        fi
    done &&
        /home/bryan/Dropbox/config/lemonbar/panel &
else
    /home/bryan/Dropbox/config/lemonbar/panel &
fi
