#!/bin/bash

if [[ "$1" == "--dry" ]]; then
    dry_run=true
    shift
fi

REMOVE_ON_EXIT=()

sshot_file="$(mktemp /tmp/shot-XXX.png)"
rm -rf "${sshot_file}"
REMOVE_ON_EXIT+=("${sshot_file}")

scrot_err="$(mktemp /tmp/scrot-XXX.err)"
REMOVE_ON_EXIT+=("${scrot_err}")

trap 'rm -rf ${REMOVE_ON_EXIT[@]}' INT TERM EXIT

release_mod_keys
if ! scrot -s "${sshot_file}" 2> "${scrot_err}"; then
    1>&2 printf \
        "[ERROR]: Failed to take a screenshot with 'scrot'.\n\n%s\n" \
        "$(cat "${scrot_err}")"
    exit 1
fi

if [[ "${dry_run}" != true ]]; then
    lpr "${sshot_file}"
fi
printf "Printing screenshot...\n"
