#!/bin/bash

######################################################
#  Prints the Name of the Currently Focused Desktop  #
######################################################

wmctrl -d | grep "\*" | awk '{print $NF}'
