#!/usr/bin/env python

"""Used to automate the demonstration of a terminal program for the purpose of creating a GIF

Automates keypresses with xdotool by reading from a simple text file. Sends most text to `xdotool
type` but also uses various "flags" embedded in the text to indicate that some event should occur
at the point the flag was found.

Flags:
    newline:    At every new line, `xdotool key KP_Enter` is run. Execution then sleeps
                for a default amount of time. This can be changed by using a <<N>> marker
                at the start of a newline. This will overwrite (NOT add to) the default
                "enter key delay" for this line only.
    [KEY]:      Emulate some special key-press using `xdotool key`. KEY is used to represent
                a template value to be replaced by a valid value (i.e. [KEY] is not a valid flag).
                Valid key flags: [ESC] [TAB] [CLEAR]
    <<N>>:      Run time.sleep(N).
    ((N)):      Alter the --delay parameter for `xdotool type`. This persists to the end
                of the line (or until the next ((N))) marker is reached). The next line
                uses the default --delay value.
"""

import re
import os
import subprocess as sp  # noqa: F401
import time

import gutils

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

log = gutils.logging.getEasyLogger(__name__)
scriptname = os.path.basename(os.path.realpath(__file__))


def main(args):
    sp.check_call(['peek', '-s'])  # start all active 'peek' sessions

    with open('/tmp/{}.pid'.format(scriptname), 'w') as f:
        f.write(str(os.getpid()))

    time.sleep(args.start_delay)
    first = True
    for line in open(args.file, 'r'):
        if line[0] == '#' or line[:2] == '//':
            continue
        if not first:
            enter_delay_match = re.search(r'^<<([0-9\.]+)>>', line)
            if enter_delay_match:
                enter_delay = enter_delay_match.groups()[0]
                line = line[enter_delay_match.end():]
            else:
                enter_delay = args.enter_delay

            gutils.xkey('KP_Enter')
            time.sleep(float(enter_delay))
        else:
            first = False

        process_line(line)

    sp.check_call(['peek', '-p'])  # stop all active 'peek' sessions


def process_line(line):
    """Processes a single line by parsing through the defined flags

    Args:
        line (str): A line from the demo text file.
    """
    pttrn_fmt = r'(<<[0-9\.]+>>|\(\([0-9\.]+\)\)|{})'
    key_flag_pairs = [('ESC', 'Escape'), ('CLEAR', 'ctrl+u'), ('TAB', 'Tab')]
    key_flag_pttrn = '|'.join([r'\[{}\]'.format(flag) for flag, _ in key_flag_pairs])
    pttrn = pttrn_fmt.format(key_flag_pttrn)

    typedelay = None
    flag = re.search(pttrn, line)
    while flag:
        gutils.xtype(line[:flag.start()], delay=typedelay)
        group = flag.groups()[0]

        for key_flag, key in key_flag_pairs:
            if group == '[{}]'.format(key_flag):
                gutils.xkey(key)
                break

        # these checks are only relevant if no key_flag was identified
        if group[:2] == '<<':
            time.sleep(float(group.strip('<>')))
        elif group[:2] == '((':
            typedelay = group.strip('()')

        line = line[flag.end():]

        flag = re.search(pttrn, line)

    # Normal `xdotool type` if no flags are found/left.
    gutils.xtype(line, delay=typedelay)


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    parser.add_argument('file', nargs='?', default='demo.txt', help='The file to read from.')
    parser.add_argument('-D', '--start-delay', type=float, dest='start_delay', default=4,
                        help='How many seconds to sleep before starting demo? Defaults to 4.')
    parser.add_argument('-E', '--enter-delay', type=float, dest='enter_delay', default=1,
                        help='How many seconds to sleep after pressing Enter? Defaults to 1.')
    args = parser.parse_args()

    with gutils.logging.context(log, debug=args.debug, verbose=args.verbose):
        main(args)
