#!/usr/bin/expect

set timeout 120

set password [lindex $argv 0]
set host [lindex $argv 1]

spawn ssh $host.bloomberg.com
expect "Password:" {
    send "$password\r"
    expect "Password:" {
        send "$password\r"
    } "Last login:" {}
} "Last login:" {}

expect "bbugyi" {
    send ""
    interact
}
