#!/usr/bin/expect

set timeout 120

set password [lindex $argv 0]
set host [lindex $argv 1]

spawn ssh $host.bloomberg.com
expect "Last login:" {} "Password:" {
    send "$password\r"
    expect "Last login:" {} "Password:" {
        send "$password\r"
    }
}

expect "bbugyi" {
    send ""
    interact
}
