#!/usr/bin/python3

""" Wrapper for castnow """

import subprocess as sp

import gutils
import videos

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

log = gutils.logging.getEasyLogger(__name__)


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    parser.add_argument('--now', dest='castnow', action='store_true', help='Use castnow to cast.')
    args = parser.parse_args()

    with gutils.logging.context(log, debug=args.debug):
        video_file = videos.get('video')
        opts = []

        if args.castnow and video_file.endswith('.avi'):
            opts.extend(['--tomp4'])
        else:
            opts.extend(['-d', "Kelly's Chromecast!!!"])

        opts.extend([video_file])

        srt_file = videos.get('subs')
        if srt_file is not None:
            opts.extend(['-s', srt_file])

        cmd_list = ['castnow'] if args.castnow else ['gnomecast']
        cmd_list.extend(opts)
        sp.check_call(cmd_list)
