#!/usr/bin/env bash

set -e

vim -c "goto 1" \
    -c "/^\[" \
    -c "nnoremap <nowait> x :normal 0lclX<Esc>/^\[ \]<CR>" \
    -c "nnoremap - :normal 0lcl-<Esc>/^\[<CR>" \
    -c "nnoremap <Space> :s/\[.\]/[ ]/g<CR>" \
    -c "nnoremap <Leader><Space> :%s/\[.\]/[ ]/g<CR>gg/^\[<CR>" \
    -c "nnoremap <nowait> [ ?\[<CR>" \
    -c "nnoremap <nowait> ] /\[<CR>" \
    "$1"

perl -i -nE 'print s/\[.\]/[ ]/gr' "$1"
