#!/bin/bash

vim -c "goto 1" -c "/^\[" -c "nnoremap <nowait> x :normal 0lclX<Esc>/^\[ \]<CR>" -c "nnoremap - :normal 0lcl-<Esc>/^\[<CR>" -c "nnoremap <Space> :normal 0lcl <Esc>/^\[<CR>" -c "nnoremap <Leader><Space> :%s/\[.\]/[ ]/g<CR>gg/^\[<CR>" -c "nnoremap <nowait> [ ?\[<CR>" -c "nnoremap <nowait> ] /\[<CR>" "$1" && ${SED} -i 's/\[.\]/[ ]/g' "$1"
