#!/usr/bin/env bash

set -e

fname="$1"
shift

vim -c "goto 1" \
    -c "/^\[" \
    -c "nnoremap <nowait> x :normal 0lclX<Esc>:w<CR>/^\[ \]<CR>" \
    -c "nnoremap - :normal 0lcl-<Esc>:w<CR>/^\[<CR>" \
    -c "nnoremap <Space> :s/\[.\]/[ ]/g<CR>:w<CR>" \
    -c "nnoremap <Leader><Space> :%s/\[.\]/[ ]/g<CR>gg/^\[<CR>:w<CR>" \
    -c "nnoremap <nowait> [ ?\[<CR>" \
    -c "nnoremap <nowait> ] /\[<CR>" \
    "$@" \
    "${fname}"

perl 1>&2 -nE 'print if /^\[/' "${fname}"
perl -i -nE 'print s/\[.\]/[ ]/gr' "${fname}"
