#!/bin/bash

if [[ $1 == "++" ]]; then
    ft="cpp"
    shift
else
    ft="c"
fi

mkdir $1
rsync -av ~/Dropbox/var/templates/$ft/ ./$1/

for f in Makefile .lshrc; do
    sed -i "s/PROGRAM_NAME/$1/g" $1/$f
done

tmux send-keys "cd $1" "Enter"
