#!/bin/bash

active_window=$(tmux list-windows | grep "*")

case $active_window in
	*"MATLAB"* )
		clear_cmd="clc";;
	*"vim"* )
		exit 1;;
	*"ghc"* )
		clear_cmd=":! clear";;
	* )
		clear_cmd="clear";;
esac

tmux send-keys "$clear_cmd" "Enter"
