#!/bin/bash

list_windows=$(tmux list-windows)

case $list_windows in
	*"MATLAB"* )
		clear_cmd="clc";;
	*"vim"* )
		exit 1;;
	*"ghc"* )
		clear_cmd=":! clear";;
	* )
		clear_cmd="clear";;
esac

tmux send-keys "$clear_cmd" "Enter"
