#!/bin/bash

###############################################################################
#  Maintenance Script that Cleans up my Machine's Filesystem                  #
###############################################################################

# ensure running as root
if [ "$(id -u)" != "0" ]; then
	exec sudo "$0" "$@"
fi


RM=/bin/rm
SAFE_RM=/usr/bin/safe-rm


# >>> HOME
"${SAFE_RM}" -rf /home/bryan/main* &> /dev/null
for f in "core" "gccdump.s" "databases-incognito"; do
	"${RM}" -rf /home/bryan/"${f}" &> /dev/null
done

# >>> DROPBOX
DROPBOX_TMP=/home/bryan/Dropbox/tmp
"${SAFE_RM}" -rf "${DROPBOX_TMP}"
mkdir "${DROPBOX_TMP}"

find /home/bryan/Dropbox \( -name "gccdump.s" \
    -o -name "core" \
    -o -name "*'s conflicted copy*" \
    \) -delete

chown -R bryan:bryan /home/bryan/Dropbox
