#!/bin/bash

read -r -d '' doc << EOM
Use 'stow' Command to Create Symlinks for All of My Dotfiles and Scripts
EOM

# ---------- Modules ----------
source gutils.sh

# ---------- Ensure Running as root ----------
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

# ---------- Global Variables ----------
ignore_patterns=( ".*\.sh" ".*\.py" ".*\.pyc" ".*\.archive\.tar\.gz" )
ignore_flags=()
for pttrn in "${ignore_patterns[@]}"; do
    ignore_flags+=("--ignore=\"${pttrn}\"")
done

# ---------- Function Definitions ----------
function stow_it() {
    src="$1"; shift
    target="$1"; shift

    dir="${src%/*}"
    subdir="${src##*/}"

    stow --dir="${dir}" --target="${target}" "${ignore_flags[@]}" "${FLAG}" "${subdir}"
}

# ---------- Parse Command-line Arguments ----------
eval set -- "$(getopt -o "d,h,v" -l "debug,help,verbose" -- "$@")"

export USAGE_GRAMMAR=(
    "[-d] [-v] [STOW_FLAG]"
    "-h"
)

# shellcheck disable=SC2154
read -r -d '' help << EOM
$(usage)

${doc}

Positional Arguments:
    STOW_FLAG       Option flag to pass to the 'stow' command. Defaults to '-R'.

Optional Arguments:
    -d | --debug
        Enable debug mode.

    -h | --help
        View this help message.

    -v | --verbose
        Enable verbose output.
EOM

while [[ -n "$1" ]]; do
    case $1 in
       -d|--debug )
           debug=true
           ;;
       -h|--help )
           echo "${help}"
           exit 0
           ;;
       -v|--verbose )
           verbose=true
           ;;
       -- )
           shift
           break
           ;;
    esac
    shift
done

if [[ "${debug}" = true && "${verbose}" = true ]]; then
    PS4='$LINENO: '
    set -x
fi

if [[ -n "$1" ]]; then
    FLAG="$1"; shift
else
    FLAG=-R
fi

# ---------- mkdir Commands ----------
# Make sure that certain directories are not symlinked directly.
# >>> $HOME directories
home_dirs=(".vim" ".ssh")
for D in "${home_dirs[@]}"; do
    mkdir /home/bryan/"${D}" &> /dev/null
done

# >>> User Data Directories
data_dirs=("qutebrowser" "okular" "applications")
for D in "${data_dirs[@]}"; do
    mkdir /home/bryan/.local/share/"${D}" &> /dev/null
done

# >>> Other Directories
mkdir -p /usr/share/rlwrap/{filters,completions} &> /dev/null

# ---------- Main ----------
if [[ $(hostname) == "athena" ]]; then
	stow_it "/home/bryan/Dropbox/bin/cron.jobs" "/etc"
fi

##### SCRIPTS
sys_info="$(uname -a)"
if [[ "${sys_info}" == *"gentoo"* ]]; then
    stow_it "/home/bryan/Dropbox/bin/gentoo" "/usr/local/bin"
fi

if [[ "${sys_info}" == *"Debian"* ]]; then
    stow_it "/home/bryan/Dropbox/bin/debian" "/usr/local/bin"
fi

stow_it "/home/bryan/Dropbox/bin/awk" "/usr/local/bin"
stow_it "/home/bryan/Dropbox/bin/GTD" "/usr/local/bin"
stow_it "/home/bryan/Dropbox/bin/main" "/usr/local/bin"
stow_it "/home/bryan/Dropbox/bin/ProtectMyLaptop" "/usr/local/bin"
stow_it "/home/bryan/Dropbox/bin/tmux" "/usr/local/bin"
stow_it "/home/bryan/Dropbox/bin/xmonad" "/usr/local/bin"
stow_it "/home/bryan/Dropbox/bin/zathura" "/usr/local/bin"

##### MODULES / LIBRARIES / HEADERS
stow_it "/home/bryan/Dropbox/lib/python" "/usr/local/lib/python"
stow_it "/home/bryan/Dropbox/lib/C" "/usr/local/lib"
stow_it "/home/bryan/Dropbox/lib/zsh" "/usr/local/lib"
stow_it "/home/bryan/Dropbox/src" "/usr/local/src"
stow_it "/home/bryan/Dropbox/include" "/usr/local/include"

##### DOTFILES
stow_it "/home/bryan/Dropbox/home" "/home/bryan"
stow_it "/home/bryan/Dropbox/usr" "/usr"
