#!/bin/bash

action='read'

eval set -- $(getopt -o 'd' -l 'dmenu' -- "$@")
while [[ -n "$1" ]]; do
	case $1 in
		'-d'|'--dmenu')
			action='dmenu';;
		'--')
			shift
			break;;
	esac	
	shift
done

prompt="Do you really want to run \"$*\"? (y/n):"

case $action in
	'dmenu' )
		choice="$(echo | dmenu -p "$prompt")";;
	'read' )
		read -n 1 -p "$prompt " choice;;
esac

if [[ "$choice" == "y" ]]; then
	printf "\nrunning: \"$*\"\n\n"
	eval "$*"
	exit 0
else
	clear
	exit 1
fi
