#!/bin/bash

#############################################
#  Converts Open Office Documents to PDF    #
#                                           #
# On my laptop, sends documents to desktop  #
# to be converted since my laptop does not  #
# have libreoffice compiled.                #
#############################################

SCRIPT="$(basename "$0")"
TMP=/tmp/"$SCRIPT"
EXTS="\(ppt\|pptx\|odt\|doc\|docx\)"

# ---------- LAPTOP ----------
if ! type unoconv &> /dev/null; then
    ssh-athena "mkdir $TMP &> /dev/null"

    find /home/bryan/Downloads \
        -type f \
        -regex ".*\.$EXTS" \
        -execdir scp -P "$ATHENAS_SSH_PORT" {} bryan@"$ATHENAS_DDNS_HOSTNAME":"$TMP" ";" &> /dev/null

    ssh-athena "$(command -v "$SCRIPT")"

    scp -P "$ATHENAS_SSH_PORT" "bryan@$ATHENAS_DDNS_HOSTNAME:$TMP/*.pdf" /home/bryan/Downloads &> /dev/null

    ssh-athena "rm -rf $TMP"
    find /home/bryan/Downloads -type f -regex ".*\.$EXTS" -delete

    exit 0
fi

# ---------- DESKTOP ----------
[ -d "$TMP" ] || mkdir "$TMP"

find /home/bryan/Downloads /home/bryan/Sync "$TMP" \
    -type f \
    -regex ".*\.$EXTS" \
    -execdir unoconv -f pdf {} ";" \
    -execdir safe-rm {} ";"
