#!/bin/bash
# Day Planner

DIR=~/Dropbox/notes/Dayplan
DAY_FILE=$DIR/dayplan.txt
DATE_FILE=$DIR/date.txt
WEEK_FILE=$DIR/weekplan.txt
SCRATCH_FILE=$DIR/scratch.txt

DATE="$(cat $DATE_FILE)"
if [[ "$DATE" != "$(date +'%m/%d/%Y')" ]]; then
    NEW=1
    DATE_DIFF_SECS=$(($(date -d "$(date +%m/%d/%Y)" +%s) - $(date -d "$DATE" +%s)))
    DATE_DIFF=$(($DATE_DIFF_SECS / 86400))
    echo $DATE_DIFF
else
    NEW=0
fi

# Remove swap files
if [ -f $DIR/.dayplan.txt.swp ]; then
    rm $DIR/.dayplan.txt.swp
fi
if [ -f $DIR/.scratch.txt.swp ]; then
    rm $DIR/.scratch.txt.swp
fi

if [ "$1" == '--new' -o "$1" == '-n' -o $NEW == 1 ]; then

    # dayplan.txt modifications
    echo "$(date +'%m/%d/%Y')" > $DATE_FILE
    sed -i -e "2,$ d" "$DAY_FILE"
    for ((i=0; i<=16; i++)); do
        printf "$(date +'%I:00%p' --date="$i hours") - \n" >> "$DAY_FILE"
        printf "$(date +'%I:30%p' --date="$i hours") - \n" >> "$DAY_FILE"
    done

    # weekplan.txt modifications
    sed -i -e "2,$(($DATE_DIFF + 1)) d" "$WEEK_FILE"
    N=$((5 - DATE_DIFF))
    if [[ $N -lt 0 ]]; then
        N=0
    fi

    while [[ $((N++)) -lt 5 ]]; do
        date -d "$N days" +"%m/%d/%Y - " >> "$WEEK_FILE"
    done

elif [ "$1" == '--collapse' -o "$1" == '-c' ]; then
    sed -i '/-\s*$/d' $DAY_FILE
fi

vim $DAY_FILE $WEEK_FILE $SCRATCH_FILE
