#!/bin/bash

. /home/bryan/Dropbox/scripts/lemonbar/panel_config

eval set -- $(getopt -o 'd' -l 'debug' -- "$@")

debug=0
while [[ -n "$1" ]]; do
	case $1 in
		'-d' | '--debug')
			debug=1;;
		'--')
			shift
			break;;
	esac
	shift
done

print_icon() {
	printf "D%%{F$1}$DBOX  \n" > $PANEL_FIFO
}

if [[ $debug -eq 1 ]]; then
	PS4='$LINENO: '
	set -x
else
	exec 2>&1
	exec 1> /dev/null
fi

COUNT=0
while true; do
	STATUS=$(dropbox-cli status)
	case $STATUS in
		'Up to date')
			(( COUNT++ ))
			print_icon $BLUE;;
		'Connecting...' | 'Starting...' | "Can't establish secure internet connection"*)
			print_icon $RED;;
		"Dropbox isn't running!")
			printf "D\n" > $PANEL_FIFO;;
		*)
			print_icon $YELLOW;;
	esac

	if (( COUNT >= 5 )); then
		exit 0
	fi
	sleep 1
done
