#!/bin/bash

. /home/bryan/Dropbox/scripts/lemonbar/panel_config

eval set -- $(getopt -o 'd' -l 'debug' -- "$@")

debug=0
while [[ -n "$1" ]]; do
	case $1 in
		'-d' | '--debug')
			debug=1;;
		'--')
			shift
			break;;
	esac
	shift
done

print_icon() {
	printf "D%%{F$1}$DBOX  \n" > $PANEL_FIFO
}

if [[ $debug -eq 0 ]]; then
	exec 2>&1
	exec 1> /dev/null
fi

COUNT=0
while true; do
	STATUS=$(dropbox-cli status)
	printf "%s\n\n" "$STATUS"
	if [[ $STATUS == "Up to date" ]]; then
		(( COUNT++ ))
		print_icon $BLUE
	elif [[ $STATUS == "Connecting..." ]] || [[ $STATUS == "Starting..." ]]; then
		print_icon $RED
	elif [[ $STATUS == "Dropbox isn't running!" ]]; then
		printf "D\n" > $PANEL_FIFO
	else
		print_icon $YELLOW
	fi

	printf "COUNT = %d\n\n" $COUNT
	if (( COUNT >= 5 )); then
		printf "Exiting...\n\n"
		exit 0
	fi
	sleep 1
done
