#!/bin/bash

CACHE_FILE=/home/bryan/Dropbox/scripts/data/dmenu_books_cache
PATH_LIST=$(find /home/bryan/Dropbox /home/bryan/Downloads -name "*.pdf" -o -name "*.epub" -o -name "*.djvu")
CHOICE=$(printf "$PATH_LIST\n" | sed -e 's/.*\///g' | cat $CACHE_FILE - | gawk '!a[$0]++' | dmenu)

eval set -- $(getopt -o "da:" -l "debug,application:" -- "$@")

application="zathura"
debug=0
while [[ -n "$1" ]]; do
    case $1 in
        '-d' | '--debug' )
            debug=1;;
        '-a' | '--application' )
            shift
            application="$1";;
        '--' )
            shift
            break;;
    esac
    shift
done

if [[ $debug -eq 1 ]]; then
	PS4='$LINENO: '
	set -x
fi

if [[ -z "$CHOICE" ]]; then
    exit 1
fi

if [[ -f $CACHE_FILE ]]; then
    sed -i "1s/^/$CHOICE\n/" $CACHE_FILE
    gawk -i inplace '!a[$0]++' $CACHE_FILE
else
    echo $CHOICE > $CACHE_FILE
fi

CHOICE_PATH=$(printf "$PATH_LIST\n" | grep -F "$CHOICE")

if [[ -z "$CHOICE_PATH" ]]; then
    ESCAPED_CHOICE=$(echo $CHOICE | sed 's/\[/\\[/g' | sed 's/\]/\\]/g')
    sed -i "/$ESCAPED_CHOICE/d" $CACHE_FILE
    notify-send -u critical "dmenu_books" "The document $CHOICE was not found. It has been purged from the cache file."
    exit 2
fi

case $application in
    'zathura' )
        xdotool key q && zathura "$CHOICE_PATH" &> /dev/null &;;
    'okular' )
        okular --unique "$CHOICE_PATH" &> /dev/null &
esac

