#!/bin/bash

CACHE_FILE=/home/bryan/Dropbox/scripts/data/dmenu_books_cache
PATH_LIST=$(find /home/bryan/Dropbox/Books -name "*.pdf" -o -name "*.epub")
CHOICE=$(printf "$PATH_LIST\n" | sed -e 's/.*\///g' | cat $CACHE_FILE - | awk '!a[$0]++' | dmenu)

if [[ -z "$CHOICE" ]]; then
    exit 1
fi

if [[ -f $CACHE_FILE ]]; then
    sed -i "1s/^/$CHOICE\n/" $CACHE_FILE
    awk '!a[$0]++' $CACHE_FILE
else
    echo $CHOICE > $CACHE_FILE
fi

xdotool key q && zathura "$(printf "$PATH_LIST\n" | grep $CHOICE)" &> /dev/null &
