#!/bin/bash

CACHE_FILE=/home/bryan/Dropbox/scripts/data/dmenu_books_cache
PATH_LIST=$(find /home/bryan/Dropbox/Books -name "*.pdf" -o -name "*.epub")
CHOICE=$(printf "$PATH_LIST\n" | sed -e 's/.*\///g' | cat $CACHE_FILE - | gawk '!a[$0]++' | dmenu)

if [[ -z "$CHOICE" ]]; then
    exit 1
fi

if [[ -f $CACHE_FILE ]]; then
    sed -i "1s/^/$CHOICE\n/" $CACHE_FILE
    gawk -i inplace '!a[$0]++' $CACHE_FILE
else
    echo $CHOICE > $CACHE_FILE
fi

CHOICE_PATH=$(printf "$PATH_LIST\n" | grep $CHOICE)

if [[ -z "$CHOICE_PATH" ]]; then
    sed -i "/$CHOICE/d" $CACHE_FILE
    notify-send -u critical "dmenu_books" "The document $CHOICE was not found. It has been purged from the cache file."
    exit 2
fi

xdotool key q && zathura "$CHOICE_PATH" &> /dev/null &
