#!/bin/bash

###################################################################################################
#  Moves configuration file(s) into my Dropbox dotfiles where they will be stowed across multiple #
#  machines.                                                                                      #
###################################################################################################

# ---------- Modules ----------
source /usr/lib/gutils.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2034
SCRIPTNAME="$(basename "$0")"
# shellcheck disable=SC2034
USAGE="usage: ${SCRIPTNAME} [-d] [-h] [-u] [-v] DOTFILE [DOTFILE [...]]" 

dropbox_dots_home=/home/bryan/Dropbox/home
parent="${PWD#/home/bryan}"

# ---------- Command-line Arguments ----------
eval set -- "$(getopt -o "d,h,v,R" -l "debug,help,verbose,reverse" -- "$@")"

read -r -d '' help << EOM
${USAGE}
EOM

while [[ -n "$1" ]]; do
    case $1 in
       -d|--debug )
           debug=true
           ;;
       -h|--help )
           echo "${help}"
           exit 0
           ;;
       -R|--reverse )
           undow=true
           ;;
       -v|--verbose )
           verbose=true
           ;;
       -- )
           shift
           break
           ;;
    esac
    shift
done

if [[ "${debug}" = true && "${verbose}" = true ]]; then
    PS4='$LINENO: '
    set -x
fi

# ---------- Main ----------

if [[ -z "$1" ]]; then
    die "${USAGE}" 2
fi

if [[ "${undow}" = true ]]; then
    action_word="Undowing"
    src="${dropbox_dots_home}"/"${parent}"
    dest="${PWD}"
else
    action_word="Dowing"
    src="${PWD}"
    dest="${dropbox_dots_home}"/"${parent}"
    mkdir "${dest}" &> /dev/null
fi

for dotfile in "$@"; do
    SRC="${src}"/"${dotfile}"
    DEST="${dest}"/"${dotfile}"

    if [[ -h "${dotfile}" ]]; then
        if [[ "${undow}" = true ]]; then
            dmsg "Removing symlink: ${dotfile}."
            safe-rm "${dotfile}"
        else
            emsg "${dotfile} is a symlink and hence cannot be dowed."
            continue
        fi
    fi

    if [[ -f "${DEST}" ]]; then
        if [[ -f "${SRC}" ]]; then
            dmsg "${DEST} Already Exists -> Removing ${SRC}."
            safe-rm "${SRC}"
        else
            emsg "Nothing to do."
            continue
        fi
    else
        dmsg "Moving ${SRC} to ${DEST}."
        mv "${SRC}" "${DEST}"
    fi

    imsg "${action_word} ${dotfile}."
done

imsg "Running clinks."
clinks
