#!/bin/bash

read -r -d '' doc <<-EOM
Moves configuration file(s) into my Sync dotfiles where they will be stowed
across multiple machines.
EOM

# ---------- Modules ----------
source bugyi.sh

# ---------- Global Variables ----------
export USAGE_GRAMMAR=(
    "[-d] [-u] [-v] DOTFILE [DOTFILE [...]]"
    "-h"
)

dropbox_dots_home="$HOME"/Sync/home
parent="${PWD#$HOME}"

# ---------- Command-line Arguments ----------
eval set -- "$(getopt -o "h,u,v" -l "help,undo,verbose" -- "$@")"

read -r -d '' help << EOM
$(usage)

${doc}

Positional Arguments:
    DOTFILE     A dotfile to dow / undow.

Optional Arguments:
    -h | --help
        View this help message.

    -u | --undo
        Undow DOTFILE.

    -v | --verbose
        Enable verbose output.
EOM

VERBOSE=0
while [[ -n "$1" ]]; do
    case $1 in
       -h|--help )
           echo "${help}"
           exit 0
           ;;
       -u|--undo )
           UNDOW=true
           ;;
       -v|--verbose )
           VERBOSE=$((VERBOSE + 1))

           # shellcheck disable=SC2034
           VERBOSE_OPT="-v"
           ;;
       -- )
           shift
           break
           ;;
    esac
    shift
done

if [[ "${VERBOSE}" -gt 1 ]]; then
    PS4='$LINENO: '
    set -x
fi

# ---------- Main ----------
if [[ -z "$1" ]]; then
    die "$(usage)" 2
fi

if [[ "${UNDOW}" = true ]]; then
    action_word="Undowing"
    src="${dropbox_dots_home}"/"${parent}"
    dest="${PWD}"
else
    action_word="Dowing"
    src="${PWD}"
    dest="${dropbox_dots_home}"/"${parent}"
    mkdir "${dest}" &> /dev/null
fi

for dotfile in "$@"; do
    SRC="${src}"/"${dotfile}"
    DEST="${dest}"/"${dotfile}"

    if [[ -h "${dotfile}" ]]; then
        if [[ "${UNDOW}" = true ]]; then
            dmsg "Removing symlink: ${dotfile}."
            safe-rm -rf "${dotfile}"
        else
            emsg "${dotfile} is a symlink and hence cannot be dowed."
            continue
        fi
    fi

    if [[ -f "${DEST}" ]]; then
        if [[ -f "${SRC}" ]]; then
            dmsg "${DEST} Already Exists -> Removing ${SRC}."
            safe-rm -rf "${SRC}"
        else
            emsg "Nothing to do."
            continue
        fi
    else
        dmsg "Moving ${SRC} to ${DEST}."
        mv "${SRC}" "${DEST}"
    fi

    imsg "${action_word} ${dotfile}."
done

imsg "Running clinks."
clinks ${VERBOSE_OPT}
