#!/bin/bash

urrent_dir="$1"

f [[ "${current_dir}" =~ "/home/bryan/Sync/home"* ]]; then
   new_dir=/home/bryan/"${current_dir##/home/bryan/Sync/home}"
lif [[ "${current_dir}" =~ "/home/bryan"* ]]; then
   #statements
   new_dir=/home/bryan/Sync/home/"${current_dir##/home/bryan}"
lse
   exit 1
i

printf "%s\n" "${new_dir}"
