#!/bin/bash

if [[ $# -lt 1 || $# -gt 2 ]]; then
    >&2 printf "usage: $(basename "$0") SESSION_NAME [ROOT]\n"
    exit 2
fi

session_name="$1"; shift
root="${1:-$HOME}"; shift

pushd "${root}" || exit 1
old_window_title="$(active_window_title)"

dvtm -t "${session_name^^}"

wtitle "${old_window_title}"
popd || exit 1
