#!/bin/bash

######################################################################
#  Runs periodic maintenance tasks meant to cleanup the filesystem.  #
######################################################################

source gutils.sh
source /home/bryan/Sync/bin/main/emaint.sh

# ---------- Main Logic ----------
D="/home/bryan/.local/share/Trash/files"
econfirm -p "Delete all files in your Trash" "sudo rm -rf $D && mkdir $D" "xprint -x 'ls -a $D'"

D="/root/.local/share/Trash/files"
xprint="$(command -v xprint)"
econfirm -p "Delete all files in root's Trash" "sudo rm -rf $D && sudo mkdir $D" "sudo ${xprint} -x 'ls -a $D'"

D="/home/bryan/Downloads"
econfirm -p "Delete all downloads" "safe-rm -rf $D && mkdir $D" "xprint -x 'ls -a $D'"

econfirm -p "Delete all log files" "sudo safe-rm /var/tmp/*.log" "xprint -x 'ls -a /var/tmp/*.log'"
