#!/bin/bash

######################################################################
#  Runs periodic maintenance tasks meant to cleanup the filesystem.  #
######################################################################

source gutils.sh
source /home/bryan/Dropbox/bin/main/emaint.sh

# ---------- Main Logic ----------
if [[ "$(hostname)" == "athena" ]]; then
    econfirm "efixsets"
    econfirm "sudo eclean --deep distfiles"
fi

D="/home/bryan/.local/share/Trash/files"
econfirm "sudo rm -rf $D && mkdir $D" "xprint -x 'ls -a $D'"

D="/root/.local/share/Trash/files"
econfirm "sudo rm -rf $D && sudo mkdir $D" "sudo xprint -x 'ls -a $D'"

D="/home/bryan/Downloads"
econfirm "safe-rm -rf $D && mkdir $D" "xprint -x 'ls -a $D'"

econfirm "sudo safe-rm /var/tmp/*.log" "xprint -x 'ls -a /var/tmp/*.log'"

econfirm "sudo updatedb"
