#!/bin/bash

SCRIPTNAME="$(basename "$0")"

PIPX_PACKAGES=(
    argcomplete
    /home/bryan/projects/black
    bump2version
    /home/bryan/projects/clipster
    flake8
    grip
    isort
    khal
    litecli
    mypy
    pip-tools
    pipenv
    poetry
    pre-commit
    pyfunky
    pylint
    trash-cli
)

function main() {
    for pack in "${PIPX_PACKAGES[@]}"; do
        pack_name="$(basename "${pack}")"
        if pipx_has_installed "${pack_name}"; then
            printf -- "----- %s is already installed.\n" "${pack_name}"
        else
            if [[ "${pack}" == "${pack_name}" ]]; then
                confirm "pipx install ${pack}"
            else
                confirm "pipx install -e ${pack}"
            fi
        fi
    done

    confirm "pipx upgrade-all"
}

if [[ "${SCRIPTNAME}" == "$(basename "${BASH_SOURCE[0]}")" ]]; then
    main "$@"
fi
