#!/bin/bash

SCRIPTNAME="$(basename "$0")"

PIPX_PACKAGES=(
    "ansible"
    "ansible-lint"
    "argcomplete"
    "/home/bryan/projects/black"
    "bump2version"
    "/home/bryan/projects/clipster[prometheus]"
    "cruft"
    "flake8"
    "grip"
    "isort"
    "j2cli"
    "khal"
    "litecli"
    "multivisor[all]"
    "mypy"
    "pgcli"
    "pip-tools"
    "pipenv"
    "poetry"
    "pre-commit"
    "pyfunky"
    "pylint"
    "trash-cli"
)

function main() {
    pipx_list_file="$(mktemp /tmp/pipx-list-XXX.txt)"
    for pack in "${PIPX_PACKAGES[@]}"; do
        pack_name="$(basename "${pack}")"
        pack_name="$(echo "${pack_name}" | perl -nE 'print s/\[.*//gr')"

        if pipx_has_installed "${pack_name}" -f "${pipx_list_file}"; then
            printf -- "----- %s is already installed.\n" "${pack_name}"
        else
            if [[ "${pack}" == "/"* ]]; then
                confirm "pipx install -e ${pack}"
            else
                confirm "pipx install ${pack}"
            fi
        fi
    done

    rm -rf "${pipx_list_file}"
    confirm "pipx upgrade-all"
}

if [[ "${SCRIPTNAME}" == "$(basename "${BASH_SOURCE[0]}")" ]]; then
    main "$@"
fi
