#!/bin/bash

#####################################################################
  Generate System /etc Configuration Files                         #
####################################################################

y_etc=/home/bryan/Sync/etc

 >>> /etc/profile.d
udo cp -f "${my_etc}"/profile.d/* /etc/profile.d/
sudo chown -R root:root /etc/profile.d

# >>> /etc/environment
sudo cp -f "${my_etc}"/environment /etc/environment
sudo chown root:root /etc/environment
