#!/bin/bash

#####################################################################
#  Generate System /etc Configuration Files                         #
#####################################################################

my_etc=/home/bryan/Dropbox/etc

# >>> /etc/profile.d
sudo cp -f "${my_etc}"/profile.d/* /etc/profile.d/
sudo chown -R root:root /etc/profile.d

# >>> /etc/environment
sudo cp -f "${my_etc}"/environment /etc/environment
sudo chown root:root /etc/environment
