#!/bin/bash

######################################
#  Runs System Maintenance Commands  #
######################################

source gutils.sh
source /home/bryan/Sync/bin/main/emaint.sh

# ---------- Main Logic ----------
_uname_output="$(uname -a)"
sys_info="${_uname_output,,}"

# >>> GENTOO
if [[ "${sys_info}" == *"gentoo"* ]]; then
    econfirm "sudo emerge --sync" && notify "Portage Package Database Sync is Complete."
    econfirm "tmux splitw -p20 watch -c -n 3 genlop -c && tmux select-pane -l"
    econfirm "sudo emerge --ask --update --deep --newuse --keep-going @world" && notify "Portage Package Updates are Complete."
    econfirm "sudo emerge --ask --depclean"
    econfirm "sudo revdep-rebuild"
    econfirm "sudo smart-live-rebuild"
    econfirm "ebvcheck -v"
    econfirm "elogv"
    econfirm "sudo dispatch-conf"
fi

# >>> DEBIAN
if [[ "${sys_info}" == *"debian"* ]]; then
    econfirm "sudo aptitude update"
    econfirm "sudo aptitude full-upgrade"
    econfirm "sudo apt autoremove"
fi

# >>> ALL
econfirm "sudo npm update -g"
econfirm "rustup update"
econfirm "pipx upgrade-all"
econfirm "sudo updatedb &"

exit 0  # Fixes issue caused by nonzero return status from last econfirm
