#!/bin/bash

######################################
#  Runs System Update Commands       #
######################################

source gutils.sh
source /home/bryan/Sync/bin/main/emaint.sh

# ---------- Main Logic ----------
_uname_output="$(uname -a)"
sys_info="${_uname_output,,}"

# >>> GENTOO
if [[ "${sys_info}" == *"gentoo"* ]]; then
    new_msg_count="$(eselect news count new)"
    if [[ "${new_msg_count}" -gt 0 ]]; then
        printf ">>> You have ${new_msg_count} unread Gentoo news items.\n"
        eselect news list
        econfirm "eselect news read new"
    fi

    econfirm "sudo emerge -A --sync" && printf '\a'

    ewatch_proc_count="$(pgrep -f 'watch.*genlop' -c)"
    if [[ "${ewatch_proc_count}" -eq 0 ]]; then
        econfirm "ewatch"
    fi

    econfirm "sudo emerge -ADuUv --keep-going --verbose-conflicts --backtrack=50 @world" && printf '\a'
    econfirm "sudo smart-live-rebuild"
    econfirm "ebvcheck -v"
    econfirm "sudo emerge -a --depclean"
    econfirm "sudo revdep-rebuild"
    econfirm "elogv"
    econfirm "sudo dispatch-conf"
fi

# >>> DEBIAN
if [[ "${sys_info}" == *"debian"* ]]; then
    econfirm "sudo aptitude update"
    econfirm "sudo aptitude full-upgrade"
    econfirm "sudo apt autoremove"
fi

# >>> ALL
econfirm "sudo npm update --force -g"
econfirm "rustup update"
econfirm "epip_update_all"
econfirm "pipx upgrade-all"
econfirm "sudo updatedb &"

if [[ "${sys_info}" == *"gentoo"* ]]; then
    echeck_kernel_version || printf ">>> The sys-kernel/gentoo-sources package was upgraded, so the linux kernel needs to be rebuilt and reinstalled!\n"
fi

exit 0  # Fixes issue caused by nonzero return status from last econfirm
