#!/bin/bash

perseus="${1:-/mnt/perseus}"
ts_file="${perseus}"/external_backup.txt # Timestamp File
ts_file_array=("${ts_file}" "${HOME}"/.external_backup.txt)

if ! mount | grep -q "${perseus}"; then
    confirm "sudo mount -L PERSEUS ${perseus}"

    if [[ -f "${ts_file}" ]]; then
        last_backup="$(date --date=@"$(cat "${ts_file}")" +"%Y-%m-%d %H:%M:%S %Z")"
    else
        last_backup="Never?"
    fi

    printf "LAST EXTERNAL BACKUP: %s\n\n" "${last_backup}"
else
    printf ">>> ${perseus} is already mounted.\n"
fi

do_external_backup "${perseus}"

if confirm "# External Backup is Finished"; then
    confirm "date +%s | tee ${ts_file_array[*]} >/dev/null"
    confirm "sudo umount ${perseus}"
fi
