#!/bin/bash

if [[ "${1}" == "-d" ]]; then
    shift
    PS4='$LINENO: '
    set -x
fi

if [[ -n "$1" ]]; then
    if [[ "$1" =~ ^[1-9][0-9]*(\.(0|[1-9][0-9]*))*$ ]]; then
        branch="$(git_find_branch "$1")"
        git checkout "${branch}"
    else
        git checkout "$@"
    fi
else
    # shellcheck disable=SC1083
    git checkout @{-1}  # Last Branch (aka 'git checkout -')
fi
