#!/bin/bash

############################################
#  Prints GitHub Repository in SSH Format  #
############################################

source /usr/lib/gutils.sh

if [[ -z "$1" ]]; then
    die "USAGE: $(basename "$0") REPO" 
fi

REPO="$1"; shift
printf "git@github.com:bbugyi200/$REPO.git"
