#!/bin/bash

########################
#  Gets Git Repo Name  #
########################

git remote show origin | awk '/.git$/ {print $NF}' | head -n 1 | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}'
