#!/bin/bash

########################
#  Gets Git Repo Name  #
########################

repo_name="$(git remote show origin | awk '/Fetch URL:/ {print $NF}' | head -n 1 | awk -F'/' '{print $NF}')"
echo "${repo_name%%.git}"
