#!/bin/bash

###################################################################
#  Wrapper around `git log`                                       #
###################################################################

if [[ "${1}" == "-d" ]]; then
    shift
    PS4='$LINENO: '
    set -x
fi


if [[ "$1" =~ ^[1-9][0-9]*p$ ]] || [[ "$1" == "p" ]]; then
    if [[ "$1" == "p" ]]; then
        N="$(branch_commit_count)"
    else
        N="${1%p}"; shift
    fi

    i=0
    while [[ "${i}" -lt "${N}"  ]]; do
        git log --graph --skip="${i}" --max-count=1 --stat -p --color=always | less
        i="$((i + 1))"
    done

    exit 0
fi

# shellcheck disable=SC2086
if [[ -n "$1" ]]; then
    if [[ "$1" =~ ^([1-9][0-9]*|-)$ ]]; then
        if [[ "$1" == "-" ]]; then
            N="$(branch_commit_count)"
        else
            N="$1"
        fi

        git log --graph --stat --max-count="${N}" --color=always
    else
        git log --color=always "$@"
    fi
else
    git log --abbrev=4 --oneline --decorate --graph --color=always | nl -s ':  ' -v 1
fi | less ${LESS_OPTS}
