#!/bin/bash

###################################################################################################
#  Update and Push Current Git Repo using Generic Commit Message                                  #
###################################################################################################

source /usr/lib/gutils.sh

cd "$(gitdir)" || exit 1
git add .
git commit -m "Update $(gitrepo)"
git push
