#!/bin/bash

if [[ "$1" == "-d" ]]; then
    PS4='$LINENO: '
    set -x; shift
fi

BRANCH="$1"; shift
ISSUE_NUMBER="${BRANCH%%-*}"

task start.any: stop
tsi "$ISSUE_NUMBER"

git checkout -b $BRANCH && git push --set-upstream origin $BRANCH
