#!/bin/bash

###################################################################
# A wrapper around ipython which makes it easier to select        #
# which Python version you would like to use.                     #
###################################################################

pyver="$1"
shift

if [[ -n "${pyver}" ]]; then
    pyver="$(echo "${pyver}" | perl -nE 'print s/^([1-9])([1-9])$/\1.\2/gr')"
    python=python"${pyver}"
else
    if command -v python3 &>/dev/null && [[ -z "${VIRTUAL_ENV}" ]]; then
        _python=python3
    else
        _python=python
    fi

    python="$(command -v "${_python}")"
fi

"${python}" -m IPython "$@"
