#!/bin/bash

###################################################################
# A wrapper around ipython which makes it easier to select        #
# which Python version you would like to use.                     #
###################################################################

version="$1"; shift

python="$(command -v python)"
if [[ -n "${version}" ]]; then
    version="$(echo "${version}" | perl -nE 'print s/^([1-9])([1-9])$/\1.\2/gr')"
    python=python"${version}"
fi

"${python}" -m IPython "$@"
