#!/bin/bash

eval set -- $(getopt -o 'm,d' -l 'menu,debug' -- "$@")

menu=0
debug=0
while [[ -n "$1" ]]; do
	case $1 in
		'-m' | '--menu')
			menu=1;;
		'-d' | '--debug')
			debug=1;;
		'--')
			shift
			break;;
	esac
	shift
done

if [[ $debug -eq 1 ]]; then
	PS4='$LINENO: '
	set -x
else
	exec 2>&1
	exec 1> /dev/null
fi

CLASS=${1%%[^A-Za-z\.]*}
CPATH="/$(echo $CLASS | sed 's/\./\//g')"
MATCHES=$(locate -r "/usr/share/doc/java8-openjdk/api.*$CPATH\.html")

if [[ -z "$MATCHES" ]]; then
	echo "No matching docs could be found." | tee >(logger -t "$(basename $0)")
	exit 1
fi

PS3=$'\n'">>> "

if [[ $menu -eq 1 ]]; then
	select DOC in $MATCHES; do
		google-chrome-stable $DOC &> /dev/null & disown
		echo
		exit 0
	done
else
	google-chrome-stable $(echo "$MATCHES" | head -1) &> /dev/null & disown
	exit 0
fi
