#!/usr/bin/python3

import subprocess
import sys

import gutils

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

try:
    last_task_uuid = open('/home/bryan/.task/.last_task', 'r').read()
except FileNotFoundError:
    gutils.notify('File ~/.task/.last_task does not exist.')
    sys.exit(1)

subprocess.call(['task', '+ACTIVE', 'stop'])

try:
    subprocess.check_call(['task', 'start', last_task_uuid])
except subprocess.CalledProcessError:
    gutils.notify('Failed to start last task.')
    sys.exit(1)
else:
    subprocess.call(['task_refresh'])
