#!/bin/zsh

eval set $(getopt -o 'd' -l 'debug' -- "$@")

debug=0
while [[ -n "$1" ]]; do
	case $1 in
		'-d' | '--debug')
			debug=1;;
		'--')
			shift
			break;;
	esac
	shift
done

if [[ $debug -eq 1 ]]; then
	PS4='$LINENO: '
	set -x
fi

course_file="/home/bryan/Dropbox/scripts/data/lecture_mode.sxhkd"
sxhkd_config="/home/bryan/.config/sxhkd/sxhkdrc"
tmp_sxhdk="/tmp/lecture_mode.sxhkd"

PROMPT="Lecture Mode activated!!! Course Name:"
if [[ -f $course_file ]]; then
	course_name=$(cat $course_file | dmenu -p $PROMPT)
else
	course_name=$(echo | dmenu -p $PROMPT)
fi

echo $course_name >> $course_file
gawk -i inplace '!seen[$0]++' $course_file

if [[ -z "$course_name" ]]; then
	echo "Course name left blank" | tee >(logger -t $0)
	exit 1
fi

cat $sxhkd_config > $tmp_sxhdk

read -r -d '' MAPPINGS << EOF

ctrl + n
	notepad --open --header=true $course_name

ctrl + Return
	notepad --dmenu --put=major $course_name

shift + Return
	notepad --dmenu --put=minor $course_name

alt + d
	notepad --undo $course_name

alt + x
	pkill -USR1 $(basename $0); \
	sleep 1; \
	sxhkd "$sxhkd_config" &
EOF

echo $MAPPINGS >> $tmp_sxhdk

pkill sxhkd
sleep 1
sxhkd -c "$tmp_sxhdk" &

trap 'kill 0' USR1

while true; do
	sleep 0.5
done &

wait
