#!/bin/bash

#####################################################################
#  Merge All Rocketbook Notes into One PDF File                     #
#####################################################################

shopt -s nullglob  # Avoid false array results.


function merge_pdfs() {
    D="$1"; shift
    prefix="$1"; shift
    final_pdf_name="$1"; shift

    pdf_files=("${D}"/"${prefix}"*)
    if [[ -n "${pdf_files[*]}" ]]; then
        final_pdf_path="${D}/${final_pdf_name}.pdf"
        if [[ -f  "${final_pdf_path}" ]]; then
            tmp_pdf_path="${D}"/temp.pdf

            mv "${final_pdf_path}" "${tmp_pdf_path}"
            pdfunite "${tmp_pdf_path}" "${pdf_files[@]}" "${final_pdf_path}"
            rm "${tmp_pdf_path}"
        else
            pdfunite "${pdf_files[@]}" "${final_pdf_path}"
        fi

        backup_dir="${D}"/backup
        mkdir -p "${backup_dir}" &> /dev/null
        mv "${pdf_files[@]}" "${backup_dir}"
    fi
}


for D in /home/bryan/Sync/var/notes/Rocketbook/*; do
    if [[ -d "${D}" ]]; then
        course_name="$(basename "${D}")"

        merge_pdfs "${D}" "Week" "My_${course_name}_Lecture_Notes"
        merge_pdfs "${D}" "20" "My_${course_name}_Notes"
    fi
done
