#!/usr/bin/python3

""" Uses rofi to Help Select a Video File (with subtitles) to Play in mpv """

import subprocess as sp

import gutils
import videos

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

from loguru import logger as log


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    args = parser.parse_args()

    gutils.logging.configure(__name__, debug=args.debug, verbose=args.verbose)
    video_file = videos.get('video')

    opts = [video_file]
        srt_file = videos.get('subs')

        if srt_file is not None:
            opts.extend(['--sub-file', srt_file])

        cmd_list = ['mpv']
        cmd_list.extend(opts)
        sp.check_call(cmd_list)
