#!/bin/zsh
arg=$1
base=$(basename $2)
fpath="/home/bryan/Dropbox/notes/Study/${base%pdf}txt"

open_notepad() {
	bspc node -p south -o 0.8
	termite --class="notepad" --title="notepad" -e "vim + $fpath"
}

if [[ $arg == "--open" ]]; then
	open_notepad
elif [[ $arg == "--put" ]]; then
	page=$(wmctrl -l | grep $base | tr -s ' ' | cut -d ' ' -f5 | cut -d'[' -f2 | cut -d'/' -f1)
	clip=$(xclip -selection clipboard -o)
	# if [[ $clip == *"."* ]]; then
	# 	clip=${clip%.*}
	# 	clip+="."
	# fi
	printf "\n\"" >> $fpath
	echo -n $clip >> $fpath 
	printf "\" - p%s\n\n" $page >> $fpath
	wmctrl -c notepad
	open_notepad && wmctrl -ax zathura.Zathura
fi
