#!/bin/bash

###################################################################
# Wrapper for tail command that calculates the height of the      #
# screen.                                                         #
###################################################################

N="$(($(tput lines) - 2))"
tail -n "${N}" "$@"
