#!/bin/bash

# ensure running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

if [[ "${1}" == "-d" ]]; then
    shift
    PS4='$LINENO: '
    set -x
fi

nameserver_file=/etc/resolv.conf

if pgrep openvpn &> /dev/null; then
    action="stop"
else
    if [[ -z "$1" ]]; then
        action="start"
        vpn="nyc"
    else
        action="$1"
        vpn="$2"
    fi
fi

if [ "$action" == "start" ]; then
    if pgrep "openvpn" > /dev/null; then
        printf "\n\nPIA is already running!\n\n"
        exit 1
    fi
    myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
    printf "Public IP Address: %s\n\n" "${myip}"

    cp "${nameserver_file}" /etc/resolv.tmp
    PIA_nameservers=( "209.222.18.222" "209.222.18.218" )
    for nameserver in "${PIA_nameservers[@]}"; do
        sed -i "/${nameserver}/d" "${nameserver_file}"
        printf '%s\n' "nameserver ${nameserver}" >> "${nameserver_file}"
    done

    case "$vpn" in 
        nyc)
            CONF="US New York City.conf";;
        east)
            CONF="US East.conf";;
        west)
            CONF="US West.conf";;
        *)
            CONF="$vpn.conf";;
    esac
    openvpn --mute-replay-warnings --config "/etc/openvpn/pia/$CONF" &

    sleep 7

    myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
    printf "\nPublic IP Address: %s" "${myip}"
    lock_network

elif [ "$action" == "stop" ]; then
    killall -9 openvpn

    mv /etc/resolv.tmp "${nameserver_file}"

    sleep 2
    unlock_network
fi
