#!/bin/bash

# ensure running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi


source gutils.sh


if [[ "${1}" == "-d" ]]; then
    shift; debug=true
    PS4='$LINENO: '
    set -x
fi

if [[ -z "$1" ]]; then
    action="start"
    vpn="nyc"
else
    action="$1"
    vpn="$2"
fi

if pgrep openvpn &> /dev/null; then
    if [[ "${action}" == "start" ]]; then
        die "OpenVPN is already running."
    fi
fi


nameserver_file=/etc/resolv.conf
if [ "$action" == "start" ]; then
    if pgrep "openvpn" > /dev/null; then
        printf "\n\nPIA is already running!\n\n"
        exit 1
    fi
    myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
    if [[ "${debug}" == true ]]; then
        printf "Public IP Address: %s\n\n" "${myip}"
    fi

    cp "${nameserver_file}" /etc/resolv.tmp
    PIA_nameservers=( "209.222.18.222" "209.222.18.218" )
    for nameserver in "${PIA_nameservers[@]}"; do
        sed -i "/${nameserver}/d" "${nameserver_file}"
        printf '%s\n' "nameserver ${nameserver}" >> "${nameserver_file}"
    done

    case "$vpn" in 
        nyc)
            CONF="US New York City.conf";;
        east)
            CONF="US East.conf";;
        west)
            CONF="US West.conf";;
        *)
            CONF="$vpn.conf";;
    esac
    openvpn --mute-replay-warnings --config "/etc/openvpn/pia/$CONF" &

    myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"

    if [[ "${debug}" == true ]]; then
        sleep 7
        printf "\nPublic IP Address: %s" "${myip}"
    fi

    lock_network
elif [ "$action" == "stop" ]; then
    killall -9 openvpn

    mv /etc/resolv.tmp "${nameserver_file}"

    unlock_network
fi
