#!/bin/bash

name="${1/.py/}"; shift

pyfile="$(find ~/Sync/bin -name "${name}".py)"
if [[ -z "${pyfile}" ]]; then
    1>&2 printf "[ERROR] Could not find python script:  '${name}.py'\n"
    exit 1
fi

tmux send-keys "clear && pushd ~/Sync/bin &> /dev/null && vim ${pyfile} ~/Sync/bin/tests/test_${name}.py && popd &> /dev/null && clear" "Enter"
