#!/bin/bash

if [[ -n "$1" ]]; then
	hostname="$1"
else
	hostname="google.com"
fi

i=0
until ping -c1 "${hostname}" &> /dev/null; do
    sleep 1
	if [[ "${i}" -gt 1800 ]]; then
		notify-send -t 0 "***** FAILED TO CONNECT TO ${hostname} *****"
		exit 1
	fi

	i=$((i + 1))
done

notify-send -t 0 "***** CONNECTION ESTABLISHED TO ${hostname} *****"
