#!/usr/bin/python3

"""Hashs the provided command-line argument."""

import hashlib
import os  # noqa: F401
import subprocess as sp  # noqa: F401
import sys  # noqa: F401

import gutils

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

from loguru import logger as log
scriptname = os.path.basename(os.path.realpath(__file__))


def main(args):
    hash_ = int(hashlib.sha1(args.target.encode()).hexdigest(), 16) % (10 ** args.digits)
    print(hash_)


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    parser.add_argument('target', help='Target to hash.')
    parser.add_argument('digits', nargs='?', type=int, default=8,
                        help='Specifies the number of digits the final hash value with have.')
    args = parser.parse_args()

    gutils.logging.configure(__name__, debug=args.debug, verbose=args.verbose)
    main(args)
