#!/bin/bash

###############################################################################
#  Wrapper for umpv. Used by qutebrowser key bindings.                        #
###############################################################################

if [[ "$(wmctrl -lx | awk '{print $3}')" != *".mpv"* ]]; then
    xdotool key super+bracketright
    xspawn -w mpv umpv "$@"
else
    umpv "$@"
fi
