#!/bin/bash

active_window=$(tmux list-windows | grep "*")

case $active_window in
	*"ghc"* )
		quit_cmd=":quit";;
	*"vim"* )
		quit_cmd=":q";;
	* )
		quit_cmd="exit";;
esac

tmux send-keys "$quit_cmd" "Enter"
