#!/bin/bash

filename=$(rofi -p "Screenshot Filename?" -dmenu)
fpath=/home/bryan/Sync/var/receipts/"$filename".png

release_mod_keys
scrot -s "${fpath}"
notify-send -u low "Saved receipt to: ${fpath}"
