#!/bin/bash

function init_scratchpad() {
    termite --class="scratchpad" --title="scratchpad" -d /home/bryan/Sync/var/notes -e $SHELL &
}

id=$(wmctrl -l | grep scratchpad | tr -s ' ' | cut -d ' ' -f1)

if [[ -z "$id" ]]; then
    init_scratchpad
    sleep 0.25 &&
    id=$(wmctrl -l | grep scratchpad | tr -s ' ' | cut -d ' ' -f1)
fi

bspc node $id --flag hidden
bspc node -f $id
