#!/bin/bash

###################################################################
#  Send Email to my Evernote Address                              #
###################################################################

# ensure running as root
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi

if [[ "${1}" == "-d" ]]; then
    shift
    PS4='$LINENO: '
    set -x
fi

subject="$1"; shift
body="$1"; shift

if [[ -f "${body}" ]]; then
    fpath="${body}"
    body=
    while IFS='' read -r line || [[ -n "${line}" ]]; do
        if [[ -z "${body}" ]]; then
            body="$(printf "%s" "${line}")"
            continue
        fi

        body="$(printf "%s<br />%s" "${body}" "${line}")"
    done < "${fpath}"
fi

read -r -d '' header <<-EOM
To: bryanbugyi34.c054be4@m.evernote.com 
Subject: ${subject}
Content-Type: text/html
EOM

email="$(printf "%s\n\n%s<br />" "${header}" "${body}")"

fp_email=/tmp/email.txt
printf "${email}\n" > "${fp_email}"

sendmail -t < "${fp_email}"
