#!/bin/bash

###################################################################
#  Send Email to my Evernote Address                              #
###################################################################

# ensure running as root
if [ "$(id -u)" != "0" ]; then
    exec sudo -E "$0" "$@"
fi

if [[ "${1}" == "-d" ]]; then
    shift
    PS4='$LINENO: '
    set -x
fi

subject="$1"; shift

pymail --to=bryanbugyi34.c054be4@m.evernote.com --subject="${subject}"
