#!/bin/bash

##################################
#  Sorts Qutebrowser Quickmarks  #
##################################

QUICKMARKS_PATH=/home/bryan/Sync/home/.config/qutebrowser/quickmarks
sort $QUICKMARKS_PATH > /tmp/quickmarks
mv /tmp/quickmarks $QUICKMARKS_PATH
