#!/bin/bash

MUX_CONFIG_DIR=~/.config/tmuxinator

if [[ -z "$1" ]]; then
    tmux ls
    exit 0
fi

if [[ $1 == '--debug' ]]; then
    PS4='$LINENO: '
    set -x
    shift
fi

case $1 in
    '-'* )
        CMD=${1#-}; shift
        if [[ 'edit' == "$CMD"* ]] && [[ -z "$1" ]]; then
            tmuxinator edit $(tmux display-message -p "#S")
        else
            tmuxinator $CMD "$@"
        fi;;
    * )
        SESSION_NAME=$1; shift
        if [[ ! -f ~/Dropbox/dotfiles/.config/tmuxinator/$SESSION_NAME.yml ]]; then
            erb name=$SESSION_NAME $MUX_CONFIG_DIR/default.yml > $MUX_CONFIG_DIR/$SESSION_NAME.yml
        fi

        tmuxinator start $SESSION_NAME root=$(defaultTmuxDir --get $SESSION_NAME);;
esac
