#!/bin/bash

LA_CMD_FILE='/tmp/LocalAlias.cmd'
if [[ -f $LA_CMD_FILE ]]; then
    active_program=$(cat $LA_CMD_FILE)
else
    active_program=$(tmux display-message -p '#{window_name}')
fi

eval set -- $(getopt -o "da:" -l "debug,action:" -- "$@")

while [[ -n "$1" ]]; do
    case $1 in
        '-a' | '--action' )
            shift
            action="$1";;
        '-d' | '--debug' )
            debug=true;;
        '--' )
            shift
            break;;
    esac
    shift
done

if [[ "$debug" = true ]]; then
    PS4='$LINENO: '
    set -x
fi


case "$action" in
    'clear' )
        case $active_program in
            *"MATLAB"* )
                CMD="clc";;
            *"ghc"* )
                CMD=":! clear";;
            *"sqlite3"* )
                CMD=".shell clear";;
            *"vim"* )
                CMD=":normal zt";;
            * )
                CMD="clear";;
        esac;;
    'quit' )
        case $active_program in
            *"ghc"* )
                CMD=":quit";;
            *"sqlite3"* )
                CMD=".quit";;
            *"git"* )
                CMD="q";;
            *"python"* )
                CMD="exit()";;
            *"vim"* )
                CMD=":qa";;
            * )
                CMD="exit";;
        esac;;
    '' )
        echo "usage: $(basename $0) --action=<action>"
        exit 1;;
    * )
        case $active_program in
            *"zsh"* | *"bash"* )
                CMD=$action;;
            * )
                logger "$(basename $0): Unable to perform '$action'. Not in zsh or bash shell."
                exit 1;
        esac
esac

tmux send-keys "$CMD" "Enter"
