#!/bin/bash

##################################
#  Opens .gitignore File in vim  #
##################################

source /usr/lib/gutils.sh

GIT_ROOT="$(gitdir 2> /dev/null)"
[ -d "$GIT_ROOT" ] || die "Not a git repository."
cd "$GIT_ROOT" || exit 1
vim .gitignore
