#!/bin/bash

SCRIPTNAME="$(basename "$0")"
HISTORY_ROOT_DIR="${HOME}"/Sync/var/logs/"${SCRIPTNAME}"

function main() {
    history_dir="${HISTORY_ROOT_DIR}"/"$(date +%Y)"
    [[ -d "${history_dir}" ]] || mkdir -p "${history_dir}"
    history_f="${history_dir}"/"$(date +%m)".txt

    _today_dt_spec="$(date +%Y-%m-%d)"
    today_dt_spec="----- ${_today_dt_spec}"
    if [[ -f "${history_f}" ]] && [[ "$(cat "${history_f}")" == *"${today_dt_spec}"* ]]; then
        printf ">>> A daily checklist entry for today (%s) has already been added to the log.\n" "${_today_dt_spec}"
        sleep 0.5
        vim -c "/${_today_dt_spec}" "${history_f}"
        return 0
    fi

    tmp_f="$(mktemp /tmp/"${SCRIPTNAME}"-XXX.txt)"
    trap 'rm -rf ${tmp_f}' INT TERM EXIT

    checklist ~/Sync/var/notes/daily_tasks.txt 2> "${tmp_f}"

    clear

    if [[ "$(cat "${tmp_f}")" != *"[ ]"* ]]; then
        printf -- "\n%s\n" "${today_dt_spec}" >> "${history_f}"
        cat "${tmp_f}" >> "${history_f}"

        printf ">>> Saved completed daily checklist:  ${history_f}\n"
    fi
    
    # if ! update-daily-tasks; then
    #     vgtd-weekly-review
    #     confirm "perl -i.bak -pE 's/(?<=Days Until Weekly Review: )0/14/' ~/Sync/var/notes/daily_tasks.txt"
    # fi
    
    work_time_card="$HOME"/Sync/var/logs/work_time_card.log
    if [[ "$(hostname)" == *"bugyidesk.pr.edgelp.net"* ]]; then
        if [[ -f "${work_time_card}" ]]; then
            cp "${work_time_card}" "${work_time_card}".bak
        fi
    
        pmset -g log | grep -E "Display is turned (on|off)" >> "${work_time_card}".bak
        sort -u "${work_time_card}".bak > "${work_time_card}"
        rm "${work_time_card}".bak
    
        scp -r "gitlab-ci.pr.edgelp.net:/prod/home/bbugyi/shell-history/*" ~/Sync/var/logs/shell-history/ &> /dev/null
    fi
}

if [[ "${SCRIPTNAME}" == "$(basename "${BASH_SOURCE[0]}")" ]]; then
    main "$@"
fi
