#!/bin/bash

##############################################
#  Wrapper for editor that logs filenames.   #
##############################################

# Hack to make sure RECENTLY_EDITED_FILES_LOG is defined when using 'sudo'.
if [[ -z "${RECENTLY_EDITED_FILES_LOG}" ]]; then
    eval "$(grep "export RECENTLY_EDITED_FILES_LOG=" "$HOME"/.profile)"
fi

/usr/bin/"$(basename "$0")" "$@"

for arg in "$@"; do
    # Don't log options, only files.
    if [[ -f "${arg}" ]]; then
        # Find absolute path to file.
        if [[ "${arg}" == "/"* ]]; then
            filepath="${arg}"
        else
            filepath="$PWD"/"${arg}"
        fi

        # Don't log temporary files.
        if [[ "${filepath}" != *"/tmp/"* ]]; then
            # Remove duplicate entries.
            sed -i "/${filepath//\//\\/}/d" "${RECENTLY_EDITED_FILES_LOG}"
            echo "${filepath}" >> "${RECENTLY_EDITED_FILES_LOG}"
        fi
    fi
done
