#!/bin/bash

if [[ -n "$1" ]]; then
    logs=()
    for f in /var/tmp/"${1}" /var/log/"${1}"; do
        if [[ -f "${f}" ]]; then
            logs+=("${f}")
        fi

        if [[ -f "${f}".log ]]; then
            logs+=("${f}".log)
        fi
    done

    if [[ "${#logs}" -ne 0 ]]; then
        vim + "${logs[@]}"
    else
        exit 1
    fi
else
    vim + /var/log/messages
fi
