#!/bin/bash

############################################################################
#  usage: `wim <command>`                                                  # 
#                                                                          #
# If <command> is a script, finds script's location and opens it in vim.   #
# Otherwise, assumes <command> is an alias or function definition and      #
# searches dotfiles for it. Once found it opens that dotfile in vim and    #
# jumps to the line number of the correpsonding alias/function definition. #
############################################################################       

if [[ "$1" == "-d" ]]; then
    PS4='$LINENO: '
    set -x
    shift
fi

if [[ -z "$1" ]]; then
    echo "usage: wim <command>"
    exit 1
fi

CMD="$1"; shift
SCRIPT_PATH="$(find /home/bryan/Dropbox/bin -type f -name "$CMD")"

if [[ -n "$SCRIPT_PATH" ]]; then
    vim -c "silent! normal g;" "$SCRIPT_PATH"
else
    LOCATION="$(ag "(^(alias|function)[ ]+|^)${CMD}( \(\)|\(\)| {|=)" /home/bryan/Dropbox/home | awk -F: '{ print "+" $2 " " $1 }')"

    if [[ -z "$LOCATION" ]]; then
        printf "ERROR: unable to find '%s'." "$CMD"
        exit 1
    fi

    # LOCATION is now a string of the form "+<N> <path>"
    eval "vim $LOCATION"
fi
