#!/bin/bash

###################################################################
#  Wrapper for kr that starts Watson Tracking                     #
###################################################################

if [[ "$(watson status)" == "No "* ]]; then
	wtoggle
fi

kr "$@"
