#!/usr/bin/python3

"""Uses <CR> Markers to Iteratively Run `xdotool type KEYSTROKES` Followed by `xdotool key Return`"""

import os  # noqa: F401
import subprocess as sp  # noqa: F401
import sys  # noqa: F401

import gutils

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

log = gutils.logging.getEasyLogger(__name__)
scriptname = os.path.basename(os.path.realpath(__file__))


def main(args):
    for keys in args.keystrokes.split(args.marker):
        gutils.shell('xdotool type --delay {} "{}"'.format(args.delay, keys),
                     'xdotool key Return')


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    parser.add_argument('keystrokes')
    parser.add_argument('-m', '--marker', default='<CR>')
    parser.add_argument('-D', '--delay', default='12')
    args = parser.parse_args()

    with gutils.logging.context(log, debug=args.debug, verbose=args.verbose):
        main(args)
