#!/usr/bin/python3

"""Type out command on screen and then (optionally) execute it."""

import argparse
import subprocess as sp  # noqa: F401
import sys
import time


def main():
    # type: () -> None
    cmd = args.expression

    if args.execute:
        print('\n>>> ', end='')
    else:
        cmd = cmd.replace('\\n', '\n')

    delay_print(cmd)

    if args.execute:
        cmd = cmd.replace('\\n', '\n')
        print()
        sp.call(cmd, shell=True)
        print()


def delay_print(s):
    # type: (str) -> None
    for c in s:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(args.delay * 0.01)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('expression', help='Expression to type to STDOUT.')
    parser.add_argument(
        '-x',
        dest='execute',
        action='store_true',
        help='Execute expression as shell command.',
    )
    parser.add_argument(
        '-D',
        dest='delay',
        type=int,
        default=5,
        help='Delay (in milliseconds) when typing to STDOUT.',
    )
    args = parser.parse_args()

    main()
