#!/bin/bash

# dropbox backup
DROPBOX=/media/bryan/hercules/backup/dropbox/monthly/
mv /media/bryan/hercules/backup/dropbox/2months/ /media/bryan/hercules/backup/dropbox/3months
mv $DROPBOX /media/bryan/hercules/backup/dropbox/2months
rsync -av --delete /home/bryan/Dropbox/ $DROPBOX
date > $DROPBOX/backup.txt
