#!/bin/bash

####################################################
#  Wrapper for `emerge` that Deletes a Package(s)  #
####################################################
source gutils.sh

# ---------- Command-line Arguments  ----------
eval set -- "$(getopt -o "d,D,1" -l "debug,depclean,oneshot" -- "$@")"

while [[ -n "$1" ]]; do
    case $1 in
       -d|--debug )
           PS4='$LINENO: '
           set -x;;
       -D|--depclean )
           depclean=true
           ;;
       -1|--oneshot )
           oneshot=true
           ;;
       -- )
           shift
           break;;
    esac
    shift
done

# ---------- Main ----------
if [[ "$depclean" = true ]]; then
    OPTS=("--depclean" "--verbose")
else
    OPTS=("--unmerge")
fi

if sudo emerge --ask "${OPTS[@]}" "$@"; then
    if [[ "${oneshot}" = true ]]; then
        imsg "Using --oneshot option. Package sets will not be altered."
    else
        all_sets=( "shared" "$(hostname)" )
        for pkg in "$@"; do
            for set in "${all_sets[@]}"; do
                filename=/etc/portage/sets/"${set}"
                if grep "${pkg}" "${filename}" &> /dev/null; then
                    full_pkg="$(ecat "${pkg}")"/"${pkg}"
                    if grep -q "${full_pkg}\$" "${filename}"; then
                        imsg "Purging ${full_pkg} from @${set}."
                        sed -i "\|${full_pkg}\$|d" "${filename}"
                    fi
                fi
            done
        done
    fi
        
    imsg "Calling updatedb to update its databases."
    updatedb
else
    exit "$?"
fi
