#!/bin/bash

# ensure running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

cd /home/bryan/projects/portage-overlay || exit 1
repoman manifest
gpup
layman -s bbugyi200

if [[ -n "$1" ]]; then
	pkg="$1"; shift
	get "${pkg}"
fi
