#!/bin/bash

###################################################################
#  Mount commands needed when installing Gentoo.                  #
###################################################################

### BEFORE
#
# ```
# mount /dev/<sda-root> /mnt/gentoo
# mount /dev/<sda-boot> /mnt/gentoo/boot
# ```

### Mount Commands
mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev

### AFTER
#
# ```
# chroot /mnt/gentoo /bin/bash
# grub-install --target=x86_64-efi --efi-directory=/boot
# grub-mkconfig -o /boot/grub/grub.cfg
# ```
