#!/bin/bash

################################
#  Build ebuild Manifest File  #
################################

overlay_dir=/usr/local/portage

# ensure running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

if [[ -z "$1" ]] || [[ -z "$2" ]]; then
    echo "usage: $(basename "$0") CATEGORY PACKAGE"
    exit 2
fi

category="$1"; shift
package="$1"; shift

count="$(find /home/bryan/Downloads -name "$package*ebuild" | wc -l)"
if [[ "$count" -gt 1 ]]; then
    echo "Multiple files match that package description."
    exit 1
fi

ebuild="$(find /home/bryan/Downloads -name "$package*ebuild")"

mkdir -p "$overlay_dir"/"$category"/"$package"
mv "$ebuild" "$overlay_dir"/"$category"/"$package"/
