#!/bin/bash

EPIP_PY2_PACKAGES=(
    IPython
)

EPIP_PY3_PACKAGES=(
    IPython
    loguru  # my personal scripts use loguru
    pandas
    parameterized
    pudb
    pygobject  # clipster dependency
    requests
    selenium
    tldextract  # qute-pass dependency
    typing-extensions
    redis
    pymongo
)
EPIP_PY37_PACKAGES=(
    scalene  # CPU/Memory CLI profiling tool
)

function run() {
    pyver="$1"; shift
    packages=("$@"); shift

    epip_install -v "${pyver}" "${packages[@]}"

    printf "\n"
}

function single_version_packs() {
    local pyver="$1"; shift

    if [[ "${pyver}" == 3.7 ]]; then
        echo "${EPIP_PY37_PACKAGES[@]}"
    fi
}

run 2.7 "${EPIP_PY2_PACKAGES[@]}"

for pyver in $(python_versions | grep -v "^2" | sort -u); do
    run "${pyver}" "${EPIP_PY3_PACKAGES[@]}" $(single_version_packs "${pyver}")
done
