#!/bin/bash

if [[ -z "$1" ]]; then
    1>&2 printf "[ERROR]: Must provide python version as command-line argument.\n"
    exit 2
fi

python_version="$1"; shift
python="python${python_version}"
pypacks="$(${python} -m pip list --user --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | tr '\n' ' ')"

echo ">>> Updating pip"
"${python}" -m pip install --upgrade --user pip

if [[ "${pypacks}" == "" ]]; then
    echo ">>> All Python ${python_version} Packages are Up-to-Date"
else
    echo ">>> Updating ${pypacks}"

    # shellcheck disable=SC2086
    "${python}" -m pip install --user -U ${pypacks}
fi
