#!/bin/bash

EPIP_PY2_PACKAGES=(
    IPython
)

EPIP_PY3_PACKAGES=(
    IPython
    loguru  # my personal scripts use loguru
    pandas
    parameterized
    pudb
    pygobject  # clipster dependency
    requests
    selenium
    tldextract  # qute-pass dependency
    typing-extensions
    redis
    pymongo
)

function run() {
    pyver="$1"; shift
    packages=("$@"); shift

    epip_install -v "${pyver}" "${packages[@]}"

    printf "\n"
}

run 2.7 "${EPIP_PY2_PACKAGES[@]}"

for pyver in $(python_versions | grep -v "^2" | sort -u); do
    run "${pyver}" "${EPIP_PY3_PACKAGES[@]}"
done
