#!/usr/bin/python3

"""Prints List of Explicitly Installed Packages (Gentoo ebuilds)"""

import subprocess as sp  # noqa: F401

import gutils

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

from loguru import logger as log


def main():
    cmd_fmt = "eix --selected-file -I* --format '<installedversions:DATESORT>' | {}"

    if args.pkgname_only:
        cmd = cmd_fmt.format('cut -f3')
    else:
        cmd_fmt = cmd_fmt.format('cut -f2-3 | sort {}')

        if args.date_sort:
            cmd = cmd_fmt.format('-n')
        else:
            cmd = cmd_fmt.format('-k4')

    sp.check_call(cmd, shell=True)


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    mx_group = parser.add_mutually_exclusive_group()
    mx_group.add_argument('-D', dest='date_sort', action='store_true',
                          help='Sort list of packages by install date. Otherwise, packages will '
                               'be sorted alphabetically.')
    mx_group.add_argument('-o', dest='pkgname_only', action='store_true',
                          help="Print only the package's name (omit the install date).")
    args = parser.parse_args()

    gutils.logging.configure(__name__, debug=args.debug, verbose=args.verbose)
    main()
