#!/bin/bash

sudo emerge \
    --alert \
    --autounmask=n \
    --backtrack=50 \
    --deep \
    --keep-going \
    --newuse \
    --update \
    --verbose \
    --verbose-conflicts \
    "$@" @world
