#!/bin/bash

######################################
#  Runs System Maintenance Commands  #
######################################

source gutils.sh
source /home/bryan/Dropbox/bin/gentoo/emaint.sh

# ---------- Main Logic ----------
econfirm "epcsync"
econfirm "sudo emerge --sync" && notify "Portage Package Database Sync is Complete."
econfirm "sudo emerge --ask --update --deep --newuse --keep-going @world" && notify "Portage Package Updates are Complete."
econfirm "sudo emerge --ask --depclean"
econfirm "sudo revdep-rebuild"
econfirm "sudo smart-live-rebuild"
econfirm "sudo npm update -g"
econfirm "ebvcheck -v"
econfirm "cache_cheaders"
econfirm "sudo updatedb"
econfirm "elogv"
econfirm "sudo dispatch-conf"
