#!/bin/bash

###################################################################################################
#  cd to packages temp build directory for portage                                                #
###################################################################################################

# shellcheck disable=SC2154

# ---------- Modules ----------
source gutils.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2154,SC2034
USAGE="usage: ${SCRIPTNAME} "

# ---------- Main ----------

D="$(find /var/tmp/portage -type d -name "*$1*" 2> /dev/null)"
sudo chown -R bryan:bryan "${D}"
cd "${D}" || return 1
