#!/bin/bash

google-chrome "https://mail.google.com/mail/u/0/\#inbox" "https://calendar.google.com/calendar/r" "https://messages.google.com/web/conversations"

function xkey() { sleep 0.25 && xdotool key "$1"; }
function pin-tab() { xkey "ctrl+shift+x"; }
function next-tab() { xkey "ctrl+Tab"; }

xkey Escape
pin-tab; next-tab; pin-tab; next-tab; pin-tab; next-tab
