#!/usr/bin/env bash

####################################################################
#  usage: `mim <GLOBAL_MARK>`                                      #
#                                                                  #
# Opens vim and goes to <GLOBAL_MARK>.                             #
####################################################################

if [[ -z "$1" ]]; then
    echo "usage: mim <mark>"
    exit 2
fi

if [[ "$1" == "-d" ]] || [[ "$1" == "--debug" ]]; then
    PS4='$LINENO: '
    set -x
    shift
fi

GLOBAL_MARK=${1^^}; shift

case "$GLOBAL_MARK" in
   'A' )
       MARKED_FILE="$HOME/Sync/home/.config/aliases.sh"
       ;;
   'B' )
       MARKED_FILE="$HOME/.xmobarrc"
        ;;
    'C' )
       MARKED_FILE="$HOME/projects/CV/BryanBugyi_CV.tex"
       ;;
   'D' )
       MARKED_FILE="$HOME/Sync/home/.config/debian.sh"
       ;;
   'E' )
       MARKED_FILE='/etc/profile.d/private.sh'
        ;;
    'F' )
       MARKED_FILE="$HOME/.config/flake8"
       ;;
   'G' )
       MARKED_FILE="$HOME/Sync/home/.config/gentoo.sh"
       ;;
   'L' )
       MARKED_FILE="$HOME/Sync/home/.vim/plugins.vim"
       ;;
   'M' )
       MARKED_FILE="$HOME/.Xmodmap"
        ;;
    'P' )
       MARKED_FILE="$HOME/.profile"
       ;;
   'Q' )
       MARKED_FILE="$HOME/Sync/home/.config/qutebrowser/config.py"
       ;;
   'T' )
       MARKED_FILE="$HOME/Sync/home/.tmux.conf"
       ;;
   'V' )
       MARKED_FILE="$HOME/Sync/home/.vim/vimrc"
       ;;
   'X' )
       MARKED_FILE="$HOME/Sync/home/.xmonad/xmonad.hs"
       ;;
   'Z' )
       MARKED_FILE="$HOME/Sync/home/.zshrc"
       ;;
esac

if [[ -n "$MARKED_FILE" ]]; then
    vim -c 'silent! normal g;' -c "normal m$GLOBAL_MARK" "$MARKED_FILE"
else
    echo "ERROR: global mark not found."
    exit 1
fi
