#!/bin/bash

if [[ -n "$1" ]]; then
    vim "$(awk "BEGIN{IGNORECASE = 1} /\/[^/]*$1[^/]*$/ {printf \"%s\n\", \$0}" "${RECENTLY_EDITED_FILES_LOG}" | tail -n 1)"
else
    fpath="$(tac "${RECENTLY_EDITED_FILES_LOG}" | fzf)"
    if [[ -n "${fpath}" ]]; then
        vim "${fpath}"
    fi
fi
