#!/bin/bash

##############################################
#  Wrapper for editor that logs filepaths.   #
##############################################

# Hack to make sure RECENTLY_EDITED_FILES_LOG is defined when using 'sudo'.
if [[ -z "${RECENTLY_EDITED_FILES_LOG}" ]]; then
    eval "$(grep "export RECENTLY_EDITED_FILES_LOG=" "$HOME"/.profile)"
fi


# If file is owned by root, open using `sudo`.
if [[ -f "$1" ]] && [[ "$(stat --format '%U' "$1")" == "root" ]]; then
    sudo -E /usr/bin/"$(basename "$0")" "$@"
else
    /usr/bin/"$(basename "$0")" "$@"
fi


# Log filepaths of all files that were edited.
for arg in "$@"; do
    # Don't log options, only files.
    if [[ -f "${arg}" ]]; then
        # Find absolute path to file.
        if [[ "${arg}" == "/"* ]]; then
            filepath="${arg}"
        else
            filepath="$PWD"/"${arg}"
        fi

        # Don't log files that match these patterns.
        for ignore_pttrn in "/tmp/" ".git/"; do
            if [[ "${filepath}" == *"${ignore_pttrn}"* ]]; then
                continue
            fi
        done

        # Remove duplicate entries.
        sed -i "/${filepath//\//\\/}/d" "${RECENTLY_EDITED_FILES_LOG}"
        echo "${filepath}" >> "${RECENTLY_EDITED_FILES_LOG}"
    fi
done
