#!/bin/bash

# dropbox backup
DROPBOX=/media/bryan/hercules/backup/dropbox
rm -rf $DROPBOX/3months && mv $DROPBOX/2months $DROPBOX/3months && cp -r $DROPBOX/monthly $DROPBOX/2months
rsync -av --delete /home/bryan/Dropbox/ $DROPBOX/monthly/
date > $DROPBOX/monthly/backup.txt
