#!/usr/bin/env python3

"""Adds new inbox task to Evernote."""

import argparse  # noqa: F401
import datetime as dt  # noqa: F401
import os  # noqa: F401
from pathlib import Path  # noqa: F401
import subprocess as sp  # noqa: F401
import sys  # noqa: F401
from typing import *  # noqa: F401
from types import *  # noqa: F401

import gutils

from loguru import logger as log
scriptname = os.path.basename(os.path.realpath(__file__))


def main(args: argparse.Namespace) -> None:
    raw_out = gutils.shell('prompt Inbox')

    gutils.shell('send2en "{}"'.format(
        raw_out.strip('\'"'),
    ))

    gutils.notify('Added new task to Evernote.')


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    args = parser.parse_args()

    gutils.logging.configure(__name__, debug=args.debug, verbose=args.verbose)
    main(args)
