#!/usr/bin/env python3

"""Adds new inbox task to Evernote."""

import gutils

from loguru import logger as log  # pylint: disable=unused-import


@gutils.catch
def main() -> None:
    parser = gutils.ArgumentParser()
    args = parser.parse_args()

    gutils.logging.configure(__file__, debug=args.debug, verbose=args.verbose)
    raw_out = gutils.shell("prompt Inbox")

    gutils.shell(
        'send2en "{}"'.format(
            raw_out.strip("'\""),
        )
    )

    gutils.notify("Added new task to Evernote.")


if __name__ == "__main__":
    main()
