#!/bin/bash

############################
#  `timew delete` wrapper  #
############################

# ---------- Modules ----------
source /usr/lib/gutils.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2034
SCRIPTNAME="$(basename "$0")"

# ---------- Main ----------
task start.any: stop &> /dev/null

N="${1:-1}"
notify -u low "$(timew delete @"${N}")"

xmonad-timew
task_refresh

