#!/bin/bash

###################################################################################################
#  Lengthens the Currently Running TimeWarrior Event by N Minutes                                 #
###################################################################################################

# ---------- Modules ----------
source gutils.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2034
SCRIPTNAME="$(basename "$0")"

minutes="$1"; shift

# ---------- Main ----------
if timew &> /dev/null; then
    timew move @1 "$(date '+%H:%M' --date="${minutes} minutes ago")" :adjust
fi

xmonad-timew

