#!/bin/bash

###################################################################################################
#  Shorten TimeWarrior Interval of @1 (last event)                                                #
###################################################################################################

# ---------- Modules ----------
source gutils.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2034
SCRIPTNAME="$(basename "$0")"

# ---------- Main ----------
if timew &> /dev/null; then
    restart_task=true
fi

task start.any: stop &> /dev/null

data_dir=/tmp/"$(basename "$0")"
[[ -d "${data_dir}" ]] || mkdir "${data_dir}"

errlog="${data_dir}"/error.log

sleep 0.5
if ! timew shorten @1 "$1"mins 2> "${errlog}"; then
    notify "$(cat "${errlog}")"
fi

if [[ "${restart_task}" = true ]]; then
    sleep 0.5
    last_task
fi

xmonad-timew

