#!/bin/bash

#####################################################################
#  Toggle watson tracking.                                          #
#####################################################################

function notify() {
    notify-send -t 3000 "Watson" "$1"
}

if [[ "$(uname -a)" == *"Debian"* ]]; then
	debian-close-notifications
fi

if [[ "$(watson status)" == "No "* ]]; then
    watson start Study
    notify "Starting Watson Tracker"
else
    watson stop
    notify "Stopping Watson Tracker"
fi
