#!/bin/bash

#####################################################################
#  Track Previous Event with Watson                                 #
#####################################################################

watson start Study
watson stop
watson edit
