#!/bin/bash

#####################################################################
# Lock screen and suspend for N seconds. If system is still         #
# suspended after N seconds, wake system up and hibernate.          #
#####################################################################

# How many seconds to suspend for?
if [[ -n "$1" ]]; then
    if ! [[ "$1" =~ ^-?[1-9][0-9]*$ ]]; then
        >&2 printf "%s\n" "[ERROR] Argument MUST be an integer."
        exit 2
    fi

    N="$1"
else
    N=1800
fi

my-screenlock &
sleep 1.5

N_seconds_from_start="$(date --date="${N} seconds" +%s)"

# Suspend system for N+1 seconds.
sudo rtcwake -m mem -s $((N + 1)) &> /dev/null

if [[ "$(date +%s)" -gt "${N_seconds_from_start}" ]]; then
    sudo pm-hibernate
fi
