#!/usr/bin/env bash

# ensure running as root
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi

# Clean from standard vim
apt-get remove --purge vim vim-runtime vim-gnome vim-tiny vim-common vim-gui-common
# Vim dependency
apt-get install liblua5.1-dev luajit libluajit-5.1 python-dev python3-dev libperl-dev libncurses5-dev ruby-dev

# Clean and prepare folders
rm -rf /usr/local/share/vim
rm /usr/bin/vim
mkdir /usr/include/lua5.1/include

# Download it and compile
cd /usr/local/src/ || exit 1
git clone https://github.com/vim/vim
cd vim/src || exit 1
make distclean

./configure --with-features=huge \
            --enable-rubyinterp \
            --with-ruby-command=$(command -v ruby) \
            --enable-largefile \
            --disable-netbeans \
            --enable-python3interp=yes \
            --with-python3-config-dir=$(python3-config --configdir) \
            --enable-perlinterp \
            --enable-luainterp \
            --with-luajit \
            --enable-gui=auto \
            --enable-fail-if-missing \
            --enable-cscope

make
make install
