#!/bin/bash

stow -v --dir=/home/bryan/Dropbox/scripts --target=/usr/local/bin -R main
stow -v --dir=/home/bryan/Dropbox/scripts --target=/usr/local/bin -R config
stow -v --dir=/home/bryan/Dropbox/scripts --target=/usr/local/bin -R lemonbar
stow -v --dir=/home/bryan/Dropbox --target=/home/bryan -R dotfiles
