#!/bin/bash
if [[ $(hostname) == "athena" ]]; then
	stow -v --dir=/home/bryan/Dropbox/scripts/backup --target=/etc -R cron.jobs
fi

stow -v --dir=/home/bryan/Dropbox/scripts --target=/usr/local/bin -R main
stow -v --dir=/home/bryan/Dropbox/scripts --target=/usr/local/bin -R config
stow -v --dir=/home/bryan/Dropbox/scripts --target=/usr/local/bin -R lemonbar
stow -v --dir=/home/bryan/Dropbox --target=/home/bryan -R dotfiles
stow -v --dir=/home/bryan/Dropbox --target=/root -R dotfiles
stow -v --dir=/home/bryan/Dropbox/scripts/C --target=/usr/local/src -R src
stow -v --dir=/home/bryan/Dropbox/scripts/C --target=/usr/local/include -R include
stow -v --dir=/home/bryan/Dropbox/scripts/C --target=/usr/local/lib -R lib
