#!/bin/bash

TITLE="Maintenance Overdue!"

DAYS=$(daysSinceLast --update)
if [[ $DAYS -ge 7 ]]; then
	notify-send -u critical -t 0 "$TITLE" "You should update your computer. You haven't run a full update in $DAYS days."
fi

DAYS=$(daysSinceLast --cleanup)
if [[ $DAYS -ge 30 ]]; then
	notify-send -u critical -t 0 "$TITLE" "You should run the 'cleanup' command. The last time you ran 'cleanup' was $DAYS days ago."
fi
