#!/bin/bash

focused=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3+1}')

get_alt_desktop $focused
ALT_D="$?"

bspc node -d "^$ALT_D"
bspc desktop -f next.occupied.local
if [[ "$1" == "swap" ]]; then
    bspc monitor -f next
    move-to-next-monitor
fi
bspc desktop -f "^$ALT_D"
