#!/bin/bash

bspc subscribe monitor | while read -r line; do
    case $line in 
		monitor_remove*|monitor_add*)
			killall panel-init && panel-init
			;&
		monitor_geometry*)

          toggle_monitor &

          I=1
          M=$(bspc query -M | wc -l)
          if [[ "$M" == 1 ]]; then
            bspc monitor LVDS1 -d I II III IV V
          elif [[ "$M" == 2 ]]; then
             bspc monitor $(bspc query -M | awk NR==1) -d I II III IV V
             bspc monitor $(bspc query -M | awk NR==2) -d VI VII VIII IX X
          else
			  logger -s "Unknown Number of Monitors"
          fi
          ;;
    esac
done
