#!/bin/bash
intern=LVDS1
extern=$(xrandr | grep -o -e "DVI[^ ]*")

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto
else
    xrandr --output "$intern" --primary --output "$extern" --auto --right-of "$intern"
    BG=$(cat /tmp/current_bg.txt)
    if [[ $BG = *"holidays"* ]]; then
        sleep 1 && feh --bg-center $BG
    else
        sleep 1 && feh --bg-fill $BG
    fi
fi
