#!/bin/bash

cp /etc/resolv.conf /etc/resolv.tmp
printf '%s\n%s' 'nameserver 209.222.18.222' 'nameserver 209.222.18.218' >> /etc/resolv.conf

myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
printf "Public IP Address: %s\n\n" "${myip}"

openvpn --config /etc/openvpn/client/US-New-York-City.conf &

sleep 7

myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
printf "\nPublic IP Address: %s" "${myip}"

iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.218/32 -j ACCEPT
# iptables -A INPUT -s 192.168.0.0/24 -j ACCEPT
# iptables -A OUTPUT -d 192.168.0.0/24 -j ACCEPT
# iptables -A OUTPUT -d ${myip}/32 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 1197 -j ACCEPT
iptables -A OUTPUT -o tun+ -j ACCEPT
iptables -A OUTPUT -j REJECT --reject-with icmp-net-unreachable
