#!/bin/bash
WNAME=`xdotool getwindowfocus getwindowname`

if wmctrl -c :ACTIVE:; then
    removeEmptyWorkspace $WNAME
else
    if [[ "$(wmctrl -d | wc -l)" -le 3 ]] && [[ "$(x11screens)" -ge 2 ]]; then
        xdotool key super+backslash
    else
        removeWorkspace
    fi
fi
