#!/bin/bash
WNAME=`xdotool getwindowfocus getwindowname`

if wmctrl -c :ACTIVE:; then
    removeEmptyWorkspace $WNAME
else
    if [[ $(wmctrl -d | grep -v "NSP" | wc -l) -le 2 ]]; then
        xdotool key alt+s
    else
        removeWorkspace
    fi
fi
