#!/usr/bin/python3

"""Uses jinja2 Template Engine to Generate Xmobar Config"""

import argparse
import os

import gutils
import jinja2
from loguru import logger as log  # pylint: disable=unused-import


scriptname = os.path.basename(os.path.realpath(__file__))


@gutils.catch
def main(_args: argparse.Namespace) -> None:
    fp_xmobar_template = "/home/bryan/Sync/var/templates/template.xmobarrc"
    fp_xmobar_config = "/home/bryan/.xmobarrc"

    xdg_runtime = gutils.xdg.get("runtime")
    with open(fp_xmobar_template, "r") as f:
        contents = f.read()

    with open(fp_xmobar_config, "w") as f:
        T = jinja2.Template(contents)
        new_contents = T.render(xdg_runtime=xdg_runtime)
        f.write(new_contents)


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    ARGS = parser.parse_args()

    gutils.logging.configure(__file__, debug=ARGS.debug, verbose=ARGS.verbose)
    main(ARGS)
