#!/usr/bin/env python

"""Uses jinja2 Template Engine to Generate Xmobar Config"""

import datetime as dt  # noqa: F401
import os  # noqa: F401
import subprocess as sp  # noqa: F401
import sys  # noqa: F401

import jinja2

import gutils

############################################################################################
#  gutils library: https://github.com/bbugyi200/pylibs/tree/master/gutils                  #
############################################################################################

log = gutils.logging.getEasyLogger(__name__)
scriptname = os.path.basename(os.path.realpath(__file__))


def main(args):
    fp_xmobar_template = '/home/bryan/Dropbox/var/templates/template.xmobarrc'
    fp_xmobar_config = '/home/bryan/.xmobarrc'

    xdg_runtime = gutils.xdg.get('runtime')
    with open(fp_xmobar_template, 'r') as f:
        contents = f.read()

    with open(fp_xmobar_config, 'w') as f:
        T = jinja2.Template(contents)
        new_contents = T.render(xdg_runtime=xdg_runtime)
        f.write(new_contents)


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    args = parser.parse_args()

    with gutils.logging.context(log, debug=args.debug, verbose=args.verbose):
        main(args)
