#!/usr/bin/python3

""" Hides currently focused NSP (if one exists). """

import subprocess as sp  # noqa: F401
import sys

import gutils

from loguru import logger as log

@gutils.catch
def main(args):
    out = sp.check_output(['get_nsps'])
    NSPs = out.decode().strip()
    try:
        out = sp.check_output('active_window_name')
    except sp.CalledProcessError:
        log.debug('No window is currently focused.')
        sys.exit(0)

    wname = out.decode().strip()
    if wname in NSPs:
        log.debug('Hiding {}.'.format(wname))
        sp.check_call(['wmctrl', '-t', '0', '-r', ':ACTIVE:'])
        sys.exit(0)

    log.debug('No scratchpad found.')


if __name__ == "__main__":
    parser = gutils.ArgumentParser()
    args = parser.parse_args()

    gutils.logging.configure(__file__, debug=args.debug, verbose=args.verbose)
    main(args)
