#!/bin/bash

if [[ $(wmctrl -d | grep -v "NSP" | wc -l) -le 2 ]]; then
    exit 1
fi

getWS() { wmctrl -d | grep "*" | tr -s " " | cut -d' ' -f9; }

MAX=5
COUNT=1
OLD_WS=$(getWS)
WNAME=$1

case $WNAME in
	*"Anki"* )
        removeWorkspace;;
	* )
	while [[ $COUNT -le $MAX ]]; do
		xdotool key ctrl+alt+shift+n
		sleep 0.1

        CURR_WS=$(getWS)
		if [[ $CURR_WS != $OLD_WS ]]; then
            if [[ $CURR_WS == "NSP" ]]; then
                xdotool key alt+bracketright
            fi
			break
		fi
		COUNT=$((COUNT+1))
	done;;
esac
