#!/bin/bash

if [[ $(wmctrl -d | grep -v -c "NSP") -le 2 ]]; then
    exit 1
fi

DEBUG=false
COUNT=1
MAX_COUNT=5

wname="$1"; shift

old_ws="$(active_desktop)"
removed_empty_ws=false

case "$wname" in
	*"Anki"* )
        removeWorkspace
        exit 0;;
	* )
        while [[ $COUNT -le $MAX_COUNT ]]; do
            window_title="$(active_window_title)"
            if [[ -z "${window_title}" ]]; then
                xdotool key super+shift+r

                curr_ws=$(active_desktop)
                if [[ "${curr_ws}" != "${old_ws}" ]]; then
                    if [[ $curr_ws == "NSP" ]]; then
                        xdotool key super+equal
                    fi
                    
                    if [[ "${DEBUG}" = true ]]; then
                        removed_empty_ws=true
                        notify-send "$(basename "$0")" "Removed empty workspace after ${COUNT} attempt(s)!"
                    fi
                fi

                break
            else
                sleep 0.1
                COUNT=$((COUNT+1))
            fi
        done;;
esac


if [[ "${DEBUG}" = true ]] && [[ "${removed_empty_ws}" != true ]]; then
    notify-send "$(basename "$0")" "Workspace still doesn't appear empty after $((COUNT - 1)) attempt(s)!"
fi
