#!/bin/bash

###################################################################################################
#  Writes sunset and sunrise times to FIFO that is read by xmobar                                 #
###################################################################################################

# shellcheck disable=SC2154

# ---------- Modules ----------
source bugyi.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2154,SC2034
USAGE="usage: ${SCRIPTNAME} "
D="/home/bryan/Sync/var"
fp_sunrise="${D}"/sunrise
fp_sunset="${D}"/sunset

[ -d "${MY_XDG_RUNTIME}" ] || mkdir "${MY_XDG_RUNTIME}"
[ -p "${MY_XDG_RUNTIME}"/fifo ] || mkfifo "${MY_XDG_RUNTIME}"/fifo

# ---------- Command-line Arguments ----------
eval set -- "$(getopt -o "d,h,R,v" -l "debug,help,refresh,verbose" -- "$@")"

read -r -d '' help << EOM
${USAGE}
EOM

while [[ -n "$1" ]]; do
    case $1 in
       -d|--debug )
           debug=true
           ;;
       -h|--help )
           echo "${help}"
           exit 0
           ;;
       -R|--refresh )
           refresh=true
           ;;
       -v|--verbose )
           verbose=true
           ;;
       -- )
           shift
           break
           ;;
    esac
    shift
done

if [[ "${debug}" = true && "${verbose}" = true ]]; then
    PS4='$LINENO: '
    set -x
fi

# ---------- Main ----------
if ! xmonad_is_running; then
    exit 0
fi

set -e

if [[ "${refresh}" = true ]]; then
    suntimes rise > "${fp_sunrise}"
    suntimes set > "${fp_sunset}"
fi

R="$(cat ${fp_sunrise})"
S="$(cat ${fp_sunset})"

printf "%s / %s\n" "${R}" "${S}" > "${MY_XDG_RUNTIME}"/fifo
