#!/bin/bash

###################################################################################################
#  Writes poll-weather output to xmobar                                                           #
###################################################################################################

# shellcheck disable=SC2154

source /usr/lib/gutils.sh

fifo_path="${MY_XDG_RUNTIME}"/fifo
[ -d "${MY_XDG_RUNTIME}" ] || mkdir "${MY_XDG_RUNTIME}"
[ -p "${fifo_path}" ] || mkfifo "${fifo_path}"

/usr/local/bin/poll-weather > "${fifo_path}"
