#!/bin/bash

###################################################################################################
#  Writes poll-timew output to xmobar                                                             #
###################################################################################################

# shellcheck disable=SC2154

source gutils.sh

[ -d "${MY_XDG_RUNTIME}" ] || mkdir "${MY_XDG_RUNTIME}"
[ -p "${MY_XDG_RUNTIME}"/fifo ] || mkfifo "${MY_XDG_RUNTIME}"/fifo

/usr/local/bin/poll-timew > "${MY_XDG_RUNTIME}"/fifo

