#!/bin/bash

if [[ "$(hostname)" != *"athena"* ]]; then
    exit 0
fi

FIFO=$XDG_RUNTIME_DIR/volume.fifo

[[ -p $FIFO ]] || mkfifo "${FIFO}"

while true; do
    if pgrep xmobar > /dev/null; then
        VOLUME=$(current_volume)
        if [[ $VOLUME -eq 0 ]]; then
            NUM_OF_BANGS=0
        else
            NUM_OF_BANGS=$((VOLUME / 10 + 1))
        fi

        COLONS="::::::::::"
        PREFIX=${COLONS:0:$NUM_OF_BANGS}
        SUFFIX=${COLONS:$NUM_OF_BANGS}
        OUTPUT="${PREFIX//:/\#}$SUFFIX"

        printf "$OUTPUT\n" > "${FIFO}"
        break
    else
        sleep 5
        continue
    fi
done
