#!/bin/bash

function make_scratchpad() {
    if pgrep "scratch-run" > /dev/null; then
        killall scratch-run
    fi
    termite --class="scratchpad" --title="scratchpad" -e ~/Dropbox/scripts/scratch/scratch-run &
}

if [[ -f /tmp/scratchid ]]; then
    id=$(cat /tmp/scratchid)
else
    make_scratchpad
fi

if [[ -z "$id" ]]; then
    make_scratchpad
else
    bspc node $id --flag hidden
fi

if [[ $? -eq 1 ]]; then
    make_scratchpad
fi

bspc node -f $id
