#!/bin/bash

###################################################################################################
#  Initializes and Starts Prime (secondary) Tmux Session                                          #
###################################################################################################

# shellcheck disable=SC2154

# ---------- Modules ----------
source gutils.sh

# ---------- Global Variables ----------
# shellcheck disable=SC2154,SC2034
USAGE="usage: ${SCRIPTNAME} "

session_name="$(tm-session-name default)"

# ---------- Main ----------
henerate_prime_mux_session "${session_name}"
tm-session-root --put "${session_name}\`" "$(tm-session-root --get "${session_name}")"
tm "${session_name}\`"
