#!/bin/bash

###############################################################################
#  Initialize Default Tmuxinator Session                                      #
###############################################################################

alacritty -e zsh -c "tm Terminal" &

sleep 0.2
wtitle zsh:"$(hostname)"
fullscreen
