#!/bin/bash

#############################################
# Verifies that a terminal is open          #
#                                           #
# If so, the socket name is sent to stdout. #
# Otherwise, exit with nonzero status.      #
#############################################

pid="$(active_window_pid)"
full_name="$(wmctrl -lxp | grep $pid | awk -F ' ' '{ print $4 }')"

if [[ "$full_name" = *"URxvt" ]]; then
    app_name="$(echo $full_name | sed 's/\..*//g')"

    if [[ "$app_name" == "urxvt" ]]; then
        socket_name="default"
    else
        socket_name="$app_name"
    fi

    printf "$socket_name\n"
else
    exit 1
fi
