#!/usr/bin/env python3

"""Displays formatted tmux sessions for tmux status-line"""

import subprocess as sp  # noqa: F401

import bugyi
from bugyi import cli
from bugyi.core import catch
from loguru import logger as log


@catch
def main() -> None:
    ps = sp.check_output(["tmux", "ls"])
    out = ps.decode().strip()

    _sessions = out.split("\n")
    log.debug("_sessions: {}", _sessions)

    sessions = []
    for S in _sessions:
        T = S[: S.index(":")]

        ps = sp.check_output(["tmux", "display", "-p", "#S"])
        active_session_name = ps.decode().strip()

        if T == active_session_name:
            sessions.append("[{}]".format(T))
        else:
            sessions.append(T)

    print("  ".join(sessions), end="")


if __name__ == "__main__":
    parser = cli.ArgumentParser()
    parser.add_argument(
        "dummy",
        nargs="*",
        help=(
            "Dummy argument. Allows the active session name to be passed in as"
            " a command-line argument, but this script does not use this"
            " argument in any way. Sending in the active session name as an"
            " argument forces tmux to update the status-line properly."
        ),
    )
    args = parser.parse_args()

    bugyi.logging.configure(__file__, debug=args.debug, verbose=args.verbose)
    main()
